pthread_cleanup_pop=pthread_cleanup_pop(execute) => __self->__cleanup_stack = __handler.__next; if (execute) (__handler.__routine)(__handler.__arg); }
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_3_2=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_3_2(x)
PTHREAD_PROCESS_SHARED=PTHREAD_PROCESS_SHARED => 1
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_3_0=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_3_0(x)
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_3_1=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_3_1(x)
FPE_INTDIV=FPE_INTDIV => 7
_POSIX_SS_REPL_MAX=_POSIX_SS_REPL_MAX => 4
_POSIX_V7_ILP32_OFF32=_POSIX_V7_ILP32_OFF32 => __ILP32_OFF32
_SC_TIMER_MAX=_SC_TIMER_MAX => 52
NDEBUG=NDEBUG => 1
ILL_NOOP=ILL_NOOP => 0
RLIM_NLIMITS=RLIM_NLIMITS => 9
SEGV_NOOP=SEGV_NOOP => 0
__volatile=__volatile => volatile
ILL_ILLADR=ILL_ILLADR => 5
SIGEMT=SIGEMT => 7
_POSIX2_CHARCLASS_NAME_MAX=_POSIX2_CHARCLASS_NAME_MAX => 14
NAME_MAX=NAME_MAX => 255
F_LOCK=F_LOCK => 1
_GLIBCXX_HAVE_MEMORY_H=_GLIBCXX_HAVE_MEMORY_H => 1
_CS_XBS5_LP64_OFF64_LDFLAGS=_CS_XBS5_LP64_OFF64_LDFLAGS => 29
RLIMIT_STACK=RLIMIT_STACK => 3
_SYS_UNISTD_H_=_SYS_UNISTD_H_
_CS_XBS5_LP64_OFF64_LIBS=_CS_XBS5_LP64_OFF64_LIBS => 30
_PC_CHOWN_RESTRICTED=_PC_CHOWN_RESTRICTED => 7
INT32_MIN=INT32_MIN => (-INT32_MAX-1)
_SC_MONOTONIC_CLOCK=_SC_MONOTONIC_CLOCK => 74
F_TLOCK=F_TLOCK => 2
CLD_KILLED=CLD_KILLED => 2
_toupper=_toupper(c) => __toupper(c)
_POSIX_SYNCHRONIZED_IO=_POSIX_SYNCHRONIZED_IO => (-1)
__AVAILABILITY__=__AVAILABILITY__
F_TEST=F_TEST => 3
__DARWIN_NULL=__DARWIN_NULL => 0
___POSIX_C_DEPRECATED_STARTING_198808L=___POSIX_C_DEPRECATED_STARTING_198808L
_GLIBCXX_HAVE_ICONV_OPEN=_GLIBCXX_HAVE_ICONV_OPEN => 1
_PTHREAD_ONCE_SIG_init=_PTHREAD_ONCE_SIG_init => 0x30B1BCBA
_SC_NPROCESSORS_ONLN=_SC_NPROCESSORS_ONLN => 58
_PC_LINK_MAX=_PC_LINK_MAX => 1
FD_ZERO=FD_ZERO(p) => __DARWIN_FD_ZERO(p)
_GLIBCXX_DEBUG_ONLY=_GLIBCXX_DEBUG_ONLY(_Statement) => ;
UINT_FAST8_MAX=UINT_FAST8_MAX => UINT8_MAX
SIGSTOP=SIGSTOP => 17
SEEK_END=SEEK_END => 2
_SC_TRACE=_SC_TRACE => 97
__LPBIG_OFFBIG=__LPBIG_OFFBIG => (-1)
___POSIX_C_DEPRECATED_STARTING_199009L=___POSIX_C_DEPRECATED_STARTING_199009L
_GLIBCXX_HAVE_LOCALE_H=_GLIBCXX_HAVE_LOCALE_H => 1
__GLIBCXX__=__GLIBCXX__ => 20070719
FPE_FLTOVF=FPE_FLTOVF => 2
_SC_SPORADIC_SERVER=_SC_SPORADIC_SERVER => 81
RLIM_SAVED_CUR=RLIM_SAVED_CUR => RLIM_INFINITY
TARGET_API_MAC_OSX=TARGET_API_MAC_OSX => 1
IOPOL_PASSIVE=IOPOL_PASSIVE => 2
SEGV_MAPERR=SEGV_MAPERR => 1
_SC_OPEN_MAX=_SC_OPEN_MAX => 5
__DARWIN_VERS_1050=__DARWIN_VERS_1050 => 1
__glibcxx_requires_string_len=__glibcxx_requires_string_len(_String, _Len)
_SYS_SYSLIMITS_H_=_SYS_SYSLIMITS_H_
PTHREAD_ONCE_INIT=PTHREAD_ONCE_INIT => {_PTHREAD_ONCE_SIG_init, {0}}
_POSIX_SPIN_LOCKS=_POSIX_SPIN_LOCKS => (-1)
_SC_SPAWN=_SC_SPAWN => 79
_STRINGS_H_=_STRINGS_H_
USER_ADDR_NULL=USER_ADDR_NULL => ((user_addr_t) 0)
_RUNE_T=_RUNE_T
__DARWIN_CLK_TCK=__DARWIN_CLK_TCK => 100
SIGABRT=SIGABRT => 6
__sfileno=__sfileno(p) => ((p)->_file)
_SC_GETGR_R_SIZE_MAX=_SC_GETGR_R_SIZE_MAX => 70
ARG_MAX=ARG_MAX => (256 * 1024)
_GLIBCXX_HAVE_INTTYPES_H=_GLIBCXX_HAVE_INTTYPES_H => 1
_PC_MAX_CANON=_PC_MAX_CANON => 2
ILL_BADSTK=ILL_BADSTK => 8
__SCHED_PARAM_SIZE__=__SCHED_PARAM_SIZE__ => 4
_SC_BC_DIM_MAX=_SC_BC_DIM_MAX => 10
OFF_MIN=OFF_MIN => LLONG_MIN
_PAIR_H=_PAIR_H => 1
CHAR_MAX=CHAR_MAX => 127
_GLIBCXX_HAVE_COPYSIGNF=_GLIBCXX_HAVE_COPYSIGNF => 1
_ISTREAM_TCC=_ISTREAM_TCC => 1
PTHREAD_INHERIT_SCHED=PTHREAD_INHERIT_SCHED => 1
_POSIX2_PBS_ACCOUNTING=_POSIX2_PBS_ACCOUNTING => (-1)
_GLIBCXX_HAVE_COPYSIGNL=_GLIBCXX_HAVE_COPYSIGNL => 1
CXA_RUNTIME_STABILITY=CXA_RUNTIME_STABILITY => "___dtrace_stability$cxa_runtime$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"
__SERR=__SERR => 0x0040
_GLIBCXX_HAVE_CEILF=_GLIBCXX_HAVE_CEILF => 1
R_OK=R_OK => (1<<2)
_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS=_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS => 11
__PROJECT_VERSION=__PROJECT_VERSION(s) => __IDSTRING(project_version,s)
_SC_PASS_MAX=_SC_PASS_MAX => 131
_GLIBCXX_HAVE_CEILL=_GLIBCXX_HAVE_CEILL => 1
FD_ISSET=FD_ISSET(n, p) => __DARWIN_FD_ISSET(n, p)
SIGKILL=SIGKILL => 9
_GLIBCXX_USE_C99_MATH_TR1=_GLIBCXX_USE_C99_MATH_TR1 => 1
_V6_ILP32_OFF32=_V6_ILP32_OFF32 => __ILP32_OFF32
_GLIBCXX_WRITE_MEM_BARRIER=_GLIBCXX_WRITE_MEM_BARRIER => __asm __volatile ("":::"memory")
SA_USERTRAMP=SA_USERTRAMP => 0x0100
_SC_XOPEN_REALTIME=_SC_XOPEN_REALTIME => 111
PRIO_DARWIN_NONUI=PRIO_DARWIN_NONUI => 0x1001
EXPR_NEST_MAX=EXPR_NEST_MAX => 32
_GLIBCXX_STRING=_GLIBCXX_STRING => 1
w_retcode=w_retcode => w_T.w_Retcode
INT_LEAST16_MIN=INT_LEAST16_MIN => INT16_MIN
_GLIBCXX_VISIBILITY=_GLIBCXX_VISIBILITY(V) => __attribute__ ((__visibility__ (#V)))
_GLIBCXX_GCC_GTHR_H=_GLIBCXX_GCC_GTHR_H
_XOPEN_ENH_I18N=_XOPEN_ENH_I18N => (1)
LINK_MAX=LINK_MAX => 32767
L_SET=L_SET => SEEK_SET
__pure2=__pure2
INT8_MIN=INT8_MIN => -128
__APPLE_API_EVOLVING=__APPLE_API_EVOLVING
_CHOWN_OK=_CHOWN_OK => (1<<21)
IOPOL_DEFAULT=IOPOL_DEFAULT => 0
__gthrw=__gthrw(name) => __gthrw2(__gthrw_ ## name,name,name)
__glibcxx_requires_sorted=__glibcxx_requires_sorted(_First, _Last)
_POSIX_MAX_INPUT=_POSIX_MAX_INPUT => 255
__DARWIN_BIG_ENDIAN=__DARWIN_BIG_ENDIAN => 4321
_POSIX_V6_ILP32_OFF32=_POSIX_V6_ILP32_OFF32 => __ILP32_OFF32
_CS_POSIX_V6_LP64_OFF64_LDFLAGS=_CS_POSIX_V6_LP64_OFF64_LDFLAGS => 9
__DARWIN_FD_COPY=__DARWIN_FD_COPY(f, t) => bcopy(f, t, sizeof(*(f)))
_GLIBCXX_CLOCALE=_GLIBCXX_CLOCALE => 1
_STRUCT_TIMESPEC=_STRUCT_TIMESPEC => struct timespec
_GLIBCXX_ATOMIC_WORD_H=_GLIBCXX_ATOMIC_WORD_H => 1
_GLIBCXX_PACKAGE_BUGREPORT=_GLIBCXX_PACKAGE_BUGREPORT => ""
_GLIBCXX_CSTDIO=_GLIBCXX_CSTDIO => 1
_CACHED_RUNES=_CACHED_RUNES => (1 <<8 )
_GLIBCXX_CTIME=_GLIBCXX_CTIME => 1
_RATTR_OK=_RATTR_OK => (1<<15)
_CODECVT_H=_CODECVT_H => 1
CLD_STOPPED=CLD_STOPPED => 5
PTHREAD_COND_INITIALIZER=PTHREAD_COND_INITIALIZER => {_PTHREAD_COND_SIG_init, {0}}
__glibcxx_function_requires=__glibcxx_function_requires(__VA_ARGS__...)
POLL_HUP=POLL_HUP => 6
_GLIBCXX_LDBL_NAMESPACE=_GLIBCXX_LDBL_NAMESPACE
MAX_INPUT=MAX_INPUT => 1024
_UINTPTR_T=_UINTPTR_T
__OSX_AVAILABLE_STARTING=__OSX_AVAILABLE_STARTING(_mac, _iphone)
_SC_IOV_MAX=_SC_IOV_MAX => 56
INT32_C=INT32_C(v) => (v)
sigmask=sigmask(m) => (1 << ((m)-1))
SI_ASYNCIO=SI_ASYNCIO => 0x10004
WORD_BIT=WORD_BIT => 32
_GLIBCXX_HAVE_MACHINE_PARAM_H=_GLIBCXX_HAVE_MACHINE_PARAM_H => 1
FPE_FLTRES=FPE_FLTRES => 4
_SC_BC_BASE_MAX=_SC_BC_BASE_MAX => 9
_CS_XBS5_ILP32_OFF32_CFLAGS=_CS_XBS5_ILP32_OFF32_CFLAGS => 20
_SC_XBS5_LPBIG_OFFBIG=_SC_XBS5_LPBIG_OFFBIG => 125
_POSIX2_PBS_TRACK=_POSIX2_PBS_TRACK => (-1)
_CS_XBS5_LPBIG_OFFBIG_CFLAGS=_CS_XBS5_LPBIG_OFFBIG_CFLAGS => 32
_SC_THREAD_SAFE_FUNCTIONS=_SC_THREAD_SAFE_FUNCTIONS => 91
SIGUSR1=SIGUSR1 => 30
SIGUSR2=SIGUSR2 => 31
__pure=__pure => __const
NL_TEXTMAX=NL_TEXTMAX => 2048
_SYS_WAIT_H_=_SYS_WAIT_H_
SIGCHLD=SIGCHLD => 20
ILL_ILLTRP=ILL_ILLTRP => 2
_WCHAR_H_=_WCHAR_H_
_CPP_TYPE_TRAITS_H=_CPP_TYPE_TRAITS_H => 1
_I386_SIGNAL_H_=_I386_SIGNAL_H_ => 1
_XOPEN_REALTIME_THREADS=_XOPEN_REALTIME_THREADS => (-1)
_SC_SHELL=_SC_SHELL => 78
LINE_MAX=LINE_MAX => 2048
__SEOF=__SEOF => 0x0020
__cplusplus=__cplusplus => 1
SIG_UNBLOCK=SIG_UNBLOCK => 2
FPE_INTOVF=FPE_INTOVF => 8
PDP_ENDIAN=PDP_ENDIAN => __DARWIN_PDP_ENDIAN
__unused=__unused
ILL_PRVREG=ILL_PRVREG => 6
ferror_unlocked=ferror_unlocked(p) => __sferror(p)
_NEW_ALLOCATOR_H=_NEW_ALLOCATOR_H => 1
_I386__ENDIAN_H_=_I386__ENDIAN_H_
_SC_BARRIERS=_SC_BARRIERS => 66
_SIZE_T=_SIZE_T
_SC_NGROUPS_MAX=_SC_NGROUPS_MAX => 4
INT_LEAST64_MIN=INT_LEAST64_MIN => INT64_MIN
_I386_LIMITS_H_=_I386_LIMITS_H_
_POSIX_V6_LP64_OFF64=_POSIX_V6_LP64_OFF64 => __LP64_OFF64
_BASIC_IOS_H=_BASIC_IOS_H => 1
_POSIX_RTSIG_MAX=_POSIX_RTSIG_MAX => 8
_GLIBCXX_HAVE_LIMIT_RSS=_GLIBCXX_HAVE_LIMIT_RSS => 1
_SC_V6_ILP32_OFFBIG=_SC_V6_ILP32_OFFBIG => 104
_C_LOCALE_H=_C_LOCALE_H => 1
UID_MAX=UID_MAX => 2147483647U
_GLIBCXX_HAVE___BUILTIN_SINF=_GLIBCXX_HAVE___BUILTIN_SINF => 1
_SC_2_FORT_RUN=_SC_2_FORT_RUN => 22
_GLIBCXX_HAVE___BUILTIN_SINL=_GLIBCXX_HAVE___BUILTIN_SINL => 1
LONG_MIN=LONG_MIN => (-2147483647L-1)
_POSIX_ASYNCHRONOUS_IO=_POSIX_ASYNCHRONOUS_IO => (-1)
RLIMIT_MEMLOCK=RLIMIT_MEMLOCK => 6
_SC_BC_STRING_MAX=_SC_BC_STRING_MAX => 12
INTPTR_MIN=INTPTR_MIN => INT32_MIN
_SC_CHILD_MAX=_SC_CHILD_MAX => 2
_PC_NAME_MAX=_PC_NAME_MAX => 4
_CHAR_TRAITS_H=_CHAR_TRAITS_H => 1
__DARWIN_LDBL_COMPAT=__DARWIN_LDBL_COMPAT(x)
_SC_SYNCHRONIZED_IO=_SC_SYNCHRONIZED_IO => 40
ULONG_MAX=ULONG_MAX => 0xffffffffUL
__SNBF=__SNBF => 0x0002
__DARWIN_FD_ISSET=__DARWIN_FD_ISSET(n, p) => __darwin_fd_isset((n), (p))
___POSIX_C_DEPRECATED_STARTING_200112L=___POSIX_C_DEPRECATED_STARTING_200112L
__glibcxx_requires_subscript=__glibcxx_requires_subscript(_N)
_POSIX_TRACE_EVENT_FILTER=_POSIX_TRACE_EVENT_FILTER => (-1)
__DARWIN_C_FULL=__DARWIN_C_FULL => 900000L
_SC_AIO_LISTIO_MAX=_SC_AIO_LISTIO_MAX => 42
_TYPEINFO=_TYPEINFO
BUS_ADRERR=BUS_ADRERR => 2
PTHREAD_SCOPE_PROCESS=PTHREAD_SCOPE_PROCESS => 2
SIG_ATOMIC_MIN=SIG_ATOMIC_MIN => INT32_MIN
_SC_DELAYTIMER_MAX=_SC_DELAYTIMER_MAX => 45
_WSTOPPED=_WSTOPPED => 0177
_GLIBCXX_HAVE_POLL=_GLIBCXX_HAVE_POLL => 1
LITTLE_ENDIAN=LITTLE_ENDIAN => __DARWIN_LITTLE_ENDIAN
_SC_SYMLOOP_MAX=_SC_SYMLOOP_MAX => 120
_LOCALE_FACETS_TCC=_LOCALE_FACETS_TCC => 1
CLK_TCK=CLK_TCK => __DARWIN_CLK_TCK
_GLIBCXX_HAVE_COSHF=_GLIBCXX_HAVE_COSHF => 1
PTHREAD_CREATE_JOINABLE=PTHREAD_CREATE_JOINABLE => 1
stdin=stdin => __stdinp
_WSTATUS=_WSTATUS(x) => (_W_INT(x) & 0177)
NL_SETMAX=NL_SETMAX => 255
_POSIX_TTY_NAME_MAX=_POSIX_TTY_NAME_MAX => 9
_SC_XOPEN_ENH_I18N=_SC_XOPEN_ENH_I18N => 109
_GLIBCXX_USE_C99=_GLIBCXX_USE_C99 => 1
OFF_MAX=OFF_MAX => LLONG_MAX
_WIN32=_WIN32 => 1
__DARWIN_WCHAR_MIN=__DARWIN_WCHAR_MIN => (-0x7fffffff - 1)
_POSIX_V7_ILP32_OFFBIG=_POSIX_V7_ILP32_OFFBIG => __ILP32_OFFBIG
__x86_64__=__x86_64__ => 1
BIG_ENDIAN=BIG_ENDIAN => __DARWIN_BIG_ENDIAN
_GLIBCXX_HAVE_COSHL=_GLIBCXX_HAVE_COSHL => 1
__DARWIN_FD_SETSIZE=__DARWIN_FD_SETSIZE => 1024
_GLIBCXX_USE_ICONV=_GLIBCXX_USE_ICONV => 1
_GLIBCXX_DEBUG_ASSERT=_GLIBCXX_DEBUG_ASSERT(_Condition)
_POSIX_MESSAGE_PASSING=_POSIX_MESSAGE_PASSING => (-1)
CHAR_MIN=CHAR_MIN => (-128)
SI_TIMER=SI_TIMER => 0x10003
_POSIX_MQ_OPEN_MAX=_POSIX_MQ_OPEN_MAX => 8
_SC_XBS5_LP64_OFF64=_SC_XBS5_LP64_OFF64 => 124
_GLIBCXX_HAVE_NL_LANGINFO=_GLIBCXX_HAVE_NL_LANGINFO => 1
CLD_EXITED=CLD_EXITED => 1
_POSIX_THREAD_DESTRUCTOR_ITERATIONS=_POSIX_THREAD_DESTRUCTOR_ITERATIONS => 4
_APPEND_OK=_APPEND_OK => (1<<13)
_RPERM_OK=_RPERM_OK => (1<<19)
_GLIBCXX_CPU_DEFINES=_GLIBCXX_CPU_DEFINES => 1
_SYS_SELECT_H_=_SYS_SELECT_H_
__DARWIN_ALIAS_STARTING=__DARWIN_ALIAS_STARTING(_mac, _iphone, x)
_CS_POSIX_V6_LPBIG_OFFBIG_LIBS=_CS_POSIX_V6_LPBIG_OFFBIG_LIBS => 13
INT_FAST32_MIN=INT_FAST32_MIN => INT32_MIN
_POSIX_TZNAME_MAX=_POSIX_TZNAME_MAX => 6
_SC_IPV6=_SC_IPV6 => 118
LC_NUMERIC=LC_NUMERIC => 4
INT_FAST16_MIN=INT_FAST16_MIN => INT16_MIN
_INT32_T=_INT32_T
_STDLIB_H_=_STDLIB_H_
__dead2=__dead2
FD_SETSIZE=FD_SETSIZE => __DARWIN_FD_SETSIZE
_GLIBCXX_HAVE_SQRTL=_GLIBCXX_HAVE_SQRTL => 1
SIGVTALRM=SIGVTALRM => 26
_POSIX_PRIORITIZED_IO=_POSIX_PRIORITIZED_IO => (-1)
PTHREAD_PRIO_NONE=PTHREAD_PRIO_NONE => 0
_FD_SET=_FD_SET
_TIME_T=_TIME_T
___POSIX_C_DEPRECATED_STARTING_199309L=___POSIX_C_DEPRECATED_STARTING_199309L
_GLIBCXX_HAVE_SQRTF=_GLIBCXX_HAVE_SQRTF => 1
L_ctermid=L_ctermid => 1024
FD_CLR=FD_CLR(n, p) => __DARWIN_FD_CLR(n, p)
_GLIBCXX_HAVE_HYPOTL=_GLIBCXX_HAVE_HYPOTL => 1
_SC_XOPEN_XCU_VERSION=_SC_XOPEN_XCU_VERSION => 121
_GLIBCXX_HAVE_HYPOTF=_GLIBCXX_HAVE_HYPOTF => 1
_POSIX_CHOWN_RESTRICTED=_POSIX_CHOWN_RESTRICTED => 200112L
__GTHREADS=__GTHREADS => 1
SA_RESETHAND=SA_RESETHAND => 0x0004
_SC_2_PBS=_SC_2_PBS => 59
UINTMAX_MAX=UINTMAX_MAX => UINT64_MAX
__APPLE_API_STANDARD=__APPLE_API_STANDARD
WIFCONTINUED=WIFCONTINUED(x) => (_WSTATUS(x) == _WSTOPPED && WSTOPSIG(x) == 0x13)
ntohl=ntohl(x) => __DARWIN_OSSwapInt32(x)
_GLIBCXX_USE_C99_STDINT_TR1=_GLIBCXX_USE_C99_STDINT_TR1 => 1
SIGCONT=SIGCONT => 19
STDERR_FILENO=STDERR_FILENO => 2
_GLIBCXX_HAVE_ATANL=_GLIBCXX_HAVE_ATANL => 1
_SC_THREAD_SPORADIC_SERVER=_SC_THREAD_SPORADIC_SERVER => 92
_GLIBCXX_HAVE_ATANF=_GLIBCXX_HAVE_ATANF => 1
ntohs=ntohs(x) => __DARWIN_OSSwapInt16(x)
WEXITED=WEXITED => 0x00000004
X_OK=X_OK => (1<<0)
_GLIBCXX_HAVE_LIMIT_VMEM=_GLIBCXX_HAVE_LIMIT_VMEM => 0
INT64_C=INT64_C(v) => (v ## LL)
RLIMIT_FSIZE=RLIMIT_FSIZE => 1
SS_ONSTACK=SS_ONSTACK => 0x0001
_POSIX2_LOCALEDEF=_POSIX2_LOCALEDEF => 200112L
_GLIBCXX_HAVE_VWSCANF=_GLIBCXX_HAVE_VWSCANF => 1
SIG_SETMASK=SIG_SETMASK => 3
_PC_NO_TRUNC=_PC_NO_TRUNC => 8
_POSIX_TIMERS=_POSIX_TIMERS => (-1)
SIGSYS=SIGSYS => 12
_FSTDIO=_FSTDIO
LONG_MAX=LONG_MAX => 2147483647L
__GTHREAD_MUTEX_INIT=__GTHREAD_MUTEX_INIT => PTHREAD_MUTEX_INITIALIZER
_ITERATOR_BASE_TYPES_H=_ITERATOR_BASE_TYPES_H => 1
INT8_MAX=INT8_MAX => 127
_SC_THREAD_CPUTIME=_SC_THREAD_CPUTIME => 84
__PTHREAD_SIZE__=__PTHREAD_SIZE__ => 596
_POSIX_THREAD_KEYS_MAX=_POSIX_THREAD_KEYS_MAX => 128
_BASIC_IOS_TCC=_BASIC_IOS_TCC => 1
_POSIX2_LINE_MAX=_POSIX2_LINE_MAX => 2048
__DARWIN_SUF_1050=__DARWIN_SUF_1050 => "$1050"
_SC_CLOCK_SELECTION=_SC_CLOCK_SELECTION => 67
__DARWIN_INODE64=__DARWIN_INODE64(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_64_BIT_INO_T)
__LINE__=__LINE__
_SC_TYPED_MEMORY_OBJECTS=_SC_TYPED_MEMORY_OBJECTS => 102
_DARWIN_FEATURE_UNIX_CONFORMANCE=_DARWIN_FEATURE_UNIX_CONFORMANCE => 3
_ALGOBASE_H=_ALGOBASE_H => 1
_EXECUTE_OK=_EXECUTE_OK => (1<<11)
_POSIX_CPUTIME=_POSIX_CPUTIME => (-1)
_POSIX_AIO_LISTIO_MAX=_POSIX_AIO_LISTIO_MAX => 2
_CXXCONFIG=_CXXCONFIG => 1
_GLIBCXX_HAVE_WCTYPE_H=_GLIBCXX_HAVE_WCTYPE_H => 1
_GLIBCXX_HAVE_EXPL=_GLIBCXX_HAVE_EXPL => 1
I386_MCONTEXT_SIZE=I386_MCONTEXT_SIZE => sizeof(struct mcontext)
_GLIBCXX_HAVE_EXPF=_GLIBCXX_HAVE_EXPF => 1
_SC_MESSAGE_PASSING=_SC_MESSAGE_PASSING => 33
_GLIBCXX_HAVE_STRTOLD=_GLIBCXX_HAVE_STRTOLD => 1
PTHREAD_SCOPE_SYSTEM=PTHREAD_SCOPE_SYSTEM => 1
_GLIBCXX_HAVE_LOG10F=_GLIBCXX_HAVE_LOG10F => 1
_GLIBCXX_HAVE_LOG10L=_GLIBCXX_HAVE_LOG10L => 1
_PTHREAD_COND_T=_PTHREAD_COND_T
_SC_PRIORITY_SCHEDULING=_SC_PRIORITY_SCHEDULING => 35
INT8_C=INT8_C(v) => (v)
_POSIX_JOB_CONTROL=_POSIX_JOB_CONTROL => 200112L
_GLIBCXX_HAVE_SIGSETJMP=_GLIBCXX_HAVE_SIGSETJMP => 1
_UNISTD_H_=_UNISTD_H_
SIGINT=SIGINT => 2
_UINT16_T=_UINT16_T
_POSIX_THREAD_PRIO_INHERIT=_POSIX_THREAD_PRIO_INHERIT => (-1)
INT16_MIN=INT16_MIN => -32768
BADSIG=BADSIG => SIG_ERR
_SC_THREAD_DESTRUCTOR_ITERATIONS=_SC_THREAD_DESTRUCTOR_ITERATIONS => 85
_GLIBCXX_HAVE_LC_MESSAGES=_GLIBCXX_HAVE_LC_MESSAGES => 1
WCOREDUMP=WCOREDUMP(x) => (_W_INT(x) & WCOREFLAG)
w_stopval=w_stopval => w_S.w_Stopval
_POSIX2_PBS_MESSAGE=_POSIX2_PBS_MESSAGE => (-1)
FD_SET=FD_SET(n, p) => __DARWIN_FD_SET(n, p)
INTPTR_MAX=INTPTR_MAX => INT32_MAX
_ACCESS_EXTENDED_MASK=_ACCESS_EXTENDED_MASK => (_READ_OK | _WRITE_OK | _EXECUTE_OK | _DELETE_OK | _APPEND_OK | _RMFILE_OK | _REXT_OK | _WEXT_OK | _RATTR_OK | _WATTR_OK | _RPERM_OK | _WPERM_OK | _CHOWN_OK)
_SC_XOPEN_LEGACY=_SC_XOPEN_LEGACY => 110
_GLIBCXX_EXT=_GLIBCXX_EXT => __gnu_cxx
__glibcxx_class_requires2=__glibcxx_class_requires2(_a, _b, _c)
__glibcxx_class_requires3=__glibcxx_class_requires3(_a, _b, _c, _d)
__glibcxx_class_requires4=__glibcxx_class_requires4(_a, _b, _c, _d, _e)
_GLIBCXX_POSTYPES_H=_GLIBCXX_POSTYPES_H => 1
_SC_SIGQUEUE_MAX=_SC_SIGQUEUE_MAX => 51
_GLIBCXX_HAVE_GTHR_DEFAULT=_GLIBCXX_HAVE_GTHR_DEFAULT => 1
_SSIZE_T=_SSIZE_T
_POSIX_MAX_CANON=_POSIX_MAX_CANON => 255
_SC_JOB_CONTROL=_SC_JOB_CONTROL => 6
__DARWIN_EXTSN_C=__DARWIN_EXTSN_C(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_EXTSN __DARWIN_SUF_NON_CANCELABLE)
_SC_TRACE_USER_EVENT_MAX=_SC_TRACE_USER_EVENT_MAX => 130
IOV_MAX=IOV_MAX => 1024
_GLIBCXX_SYMVER=_GLIBCXX_SYMVER => 1
BC_DIM_MAX=BC_DIM_MAX => 2048
_XOPEN_IOV_MAX=_XOPEN_IOV_MAX => 16
_GLIBCXX_HAVE_FREXPF=_GLIBCXX_HAVE_FREXPF => 1
_GLIBCXX_HAVE_SINF=_GLIBCXX_HAVE_SINF => 1
_GLIBCXX_HAVE_SYS_UIO_H=_GLIBCXX_HAVE_SYS_UIO_H => 1
INT_LEAST8_MAX=INT_LEAST8_MAX => INT8_MAX
_CS_POSIX_V6_LP64_OFF64_CFLAGS=_CS_POSIX_V6_LP64_OFF64_CFLAGS => 8
_GLIBCXX_READ_MEM_BARRIER=_GLIBCXX_READ_MEM_BARRIER => __asm __volatile ("":::"memory")
_GLIBCXX_HAVE_SYS_IOCTL_H=_GLIBCXX_HAVE_SYS_IOCTL_H => 1
_SC_XOPEN_STREAMS=_SC_XOPEN_STREAMS => 114
_GLIBCXX_HAVE_FREXPL=_GLIBCXX_HAVE_FREXPL => 1
_CXX_ALLOCATOR_H=_CXX_ALLOCATOR_H => 1
__glibcxx_requires_nonempty=__glibcxx_requires_nonempty()
_OS__OSBYTEORDERI386_H=_OS__OSBYTEORDERI386_H
_GLIBCXX_HAVE_SINL=_GLIBCXX_HAVE_SINL => 1
__WORDSIZE=__WORDSIZE => 32
_GLIBCXX_NUMERIC_LIMITS=_GLIBCXX_NUMERIC_LIMITS => 1
SIGILL=SIGILL => 4
_PTHREAD_FIRSTFIT_MUTEX_SIG_init=_PTHREAD_FIRSTFIT_MUTEX_SIG_init => 0x32AAABA3
_RUNETYPE_H_=_RUNETYPE_H_
__DARWIN_CTYPE_static_inline=__DARWIN_CTYPE_static_inline => static __inline
UINT8_MAX=UINT8_MAX => 255
_GLIBCXX_HAVE_MBSTATE_T=_GLIBCXX_HAVE_MBSTATE_T => 1
_POSIX_SYMLINK_MAX=_POSIX_SYMLINK_MAX => 255
_GLIBCXX_NUM_CATEGORIES=_GLIBCXX_NUM_CATEGORIES => 0
_PTHREAD_RECURSIVE_MUTEX_SIG_init=_PTHREAD_RECURSIVE_MUTEX_SIG_init => 0x32AAABA2
__DARWIN_NON_CANCELABLE=__DARWIN_NON_CANCELABLE => 0
_GLIBCXX_HAVE___SIGNBITL=_GLIBCXX_HAVE___SIGNBITL => 1
_CS_XBS5_LP64_OFF64_CFLAGS=_CS_XBS5_LP64_OFF64_CFLAGS => 28
_PC_REC_INCR_XFER_SIZE=_PC_REC_INCR_XFER_SIZE => 20
SI_MESGQ=SI_MESGQ => 0x10005
BUS_ADRALN=BUS_ADRALN => 1
_GLIBCXX_HAVE_GETPAGESIZE=_GLIBCXX_HAVE_GETPAGESIZE => 1
_SC_XOPEN_REALTIME_THREADS=_SC_XOPEN_REALTIME_THREADS => 112
_FORTIFY_SOURCE=_FORTIFY_SOURCE => 2
__sgetc=__sgetc(p) => (--(p)->_r < 0 ? __srget(p) : (int)(*(p)->_p++))
SIG_ATOMIC_MAX=SIG_ATOMIC_MAX => INT32_MAX
_SC_FILE_LOCKING=_SC_FILE_LOCKING => 69
_GLIBCXX_HAVE___SIGNBITF=_GLIBCXX_HAVE___SIGNBITF => 1
__PTHREAD_MUTEX_SIZE__=__PTHREAD_MUTEX_SIZE__ => 40
_SYS__TYPES_H_=_SYS__TYPES_H_
_POSIX_DELAYTIMER_MAX=_POSIX_DELAYTIMER_MAX => 32
UINT_FAST64_MAX=UINT_FAST64_MAX => UINT64_MAX
PTRDIFF_MAX=PTRDIFF_MAX => INT32_MAX
__DARWIN_howmany=__DARWIN_howmany(x, y) => ((((x) % (y)) == 0) ? ((x) / (y)) : (((x) / (y)) + 1))
IOPOL_TYPE_DISK=IOPOL_TYPE_DISK => 0
_QUAD_LOWWORD=_QUAD_LOWWORD => 0
SIGPIPE=SIGPIPE => 13
_GLIBCXX_HAVE_MODF=_GLIBCXX_HAVE_MODF => 1
_RLIMIT_POSIX_FLAG=_RLIMIT_POSIX_FLAG => 0x1000
EQUIV_CLASS_MAX=EQUIV_CLASS_MAX => 2
_TR1_STDARG_H=_TR1_STDARG_H => 1
INT_FAST32_MAX=INT_FAST32_MAX => INT32_MAX
_SC_2_CHAR_TERM=_SC_2_CHAR_TERM => 20
SA_NOCLDSTOP=SA_NOCLDSTOP => 0x0008
__AVAILABILITY_INTERNAL_DEPRECATED=__AVAILABILITY_INTERNAL_DEPRECATED => __attribute__((deprecated,visibility("default")))
_GLIBCXX_USE_RANDOM_TR1=_GLIBCXX_USE_RANDOM_TR1 => 1
_V6_ILP32_OFFBIG=_V6_ILP32_OFFBIG => __ILP32_OFFBIG
LONG_BIT=LONG_BIT => 32
__glibcxx_requires_partitioned=__glibcxx_requires_partitioned(_First, _Last, _Value)
ILL_PRVOPC=ILL_PRVOPC => 3
INT_FAST16_MAX=INT_FAST16_MAX => INT16_MAX
_WCTYPE_T=_WCTYPE_T
FPE_NOOP=FPE_NOOP => 0
__glibcxx_requires_sorted_pred=__glibcxx_requires_sorted_pred(_First, _Last, _Pred)
SV_RESETHAND=SV_RESETHAND => SA_RESETHAND
_POSIX_HOST_NAME_MAX=_POSIX_HOST_NAME_MAX => 255
_PC_REC_MIN_XFER_SIZE=_PC_REC_MIN_XFER_SIZE => 22
_CONCEPT_CHECK_H=_CONCEPT_CHECK_H => 1
SV_SIGINFO=SV_SIGINFO => SA_SIGINFO
MINSIGSTKSZ=MINSIGSTKSZ => 32768
_GLIBCXX_HAVE_LIMIT_DATA=_GLIBCXX_HAVE_LIMIT_DATA => 1
_POSIX_MEMORY_PROTECTION=_POSIX_MEMORY_PROTECTION => 200112L
_PC_VDISABLE=_PC_VDISABLE => 9
_SC_THREAD_PRIO_PROTECT=_SC_THREAD_PRIO_PROTECT => 88
_SC_2_C_DEV=_SC_2_C_DEV => 19
_PC_EXTENDED_SECURITY_NP=_PC_EXTENDED_SECURITY_NP => 13
LC_TIME=LC_TIME => 5
_XOPEN_SHM=_XOPEN_SHM => (1)
__used=__used
_GLIBCXX_USE_C99_COMPLEX_TR1=_GLIBCXX_USE_C99_COMPLEX_TR1 => 1
__PTHREAD_MUTEXATTR_SIZE__=__PTHREAD_MUTEXATTR_SIZE__ => 8
_GLIBCXX_HAVE_ATAN2L=_GLIBCXX_HAVE_ATAN2L => 1
_POSIX_SPAWN=_POSIX_SPAWN => (-1)
_WCTYPE_H_=_WCTYPE_H_
INT_LEAST32_MIN=INT_LEAST32_MIN => INT32_MIN
_GLIBCXX_HAVE_ATAN2F=_GLIBCXX_HAVE_ATAN2F => 1
SIGIOT=SIGIOT => SIGABRT
__DARWIN_OSSwapInt16=__DARWIN_OSSwapInt16(x) => ((__uint16_t)(__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt16(x) : _OSSwapInt16(x)))
_POSIX_TRACE_USER_EVENT_MAX=_POSIX_TRACE_USER_EVENT_MAX => 32
_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS=_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS => 6
_GLIBCXX_PACKAGE__GLIBCXX_VERSION=_GLIBCXX_PACKAGE__GLIBCXX_VERSION => "version-unused"
_POSIX_TIMER_MAX=_POSIX_TIMER_MAX => 32
_GLIBCXX_HAVE_STDINT_H=_GLIBCXX_HAVE_STDINT_H => 1
__offsetof=__offsetof(type, field) => ((size_t)(&((type *)0)->field))
_POSIX2_FORT_DEV=_POSIX2_FORT_DEV => (-1)
__attribute__=__attribute__(x)
_SC_THREAD_KEYS_MAX=_SC_THREAD_KEYS_MAX => 86
_POSIX_SEMAPHORES=_POSIX_SEMAPHORES => (-1)
_GLIBCXX_HAVE_HYPOT=_GLIBCXX_HAVE_HYPOT => 1
_GLIBCXX_HAVE_SINHL=_GLIBCXX_HAVE_SINHL => 1
_GLIBCXX_HAVE_SINHF=_GLIBCXX_HAVE_SINHF => 1
SIGXCPU=SIGXCPU => 24
__GTHREAD_RECURSIVE_MUTEX_INIT=__GTHREAD_RECURSIVE_MUTEX_INIT => PTHREAD_RECURSIVE_MUTEX_INITIALIZER
__GNUC_LIBSTD__=__GNUC_LIBSTD__ => 4
RLIMIT_DATA=RLIMIT_DATA => 2
SV_ONSTACK=SV_ONSTACK => SA_ONSTACK
__COUNTER__=__COUNTER__
_POSIX_NGROUPS_MAX=_POSIX_NGROUPS_MAX => 8
_XOPEN_UNIX=_XOPEN_UNIX => (1)
__signed=__signed => signed
PTHREAD_DESTRUCTOR_ITERATIONS=PTHREAD_DESTRUCTOR_ITERATIONS => 4
_SC_THREADS=_SC_THREADS => 96
_TEMPBUF_H=_TEMPBUF_H => 1
__DARWIN_OSSwapInt32=__DARWIN_OSSwapInt32(x) => (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt32(x) : _OSSwapInt32(x))
_SC_THREAD_PRIO_INHERIT=_SC_THREAD_PRIO_INHERIT => 87
_GLIBCXX_HAVE_ICONV_CLOSE=_GLIBCXX_HAVE_ICONV_CLOSE => 1
_MACHTYPES_H_=_MACHTYPES_H_
_GLIBCXX_HAVE_SYS_RESOURCE_H=_GLIBCXX_HAVE_SYS_RESOURCE_H => 1
_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS=_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS => 5
UINT_LEAST64_MAX=UINT_LEAST64_MAX => UINT64_MAX
_SC_MQ_OPEN_MAX=_SC_MQ_OPEN_MAX => 46
_GLIBCXX_HAVE_ISNAN=_GLIBCXX_HAVE_ISNAN => 1
_CTYPE_SW3=_CTYPE_SW3 => 0xc0000000L
PTHREAD_CANCEL_DISABLE=PTHREAD_CANCEL_DISABLE => 0x00
_SC_XOPEN_VERSION=_SC_XOPEN_VERSION => 116
_CTYPE_SW1=_CTYPE_SW1 => 0x40000000L
_POSIX_THREAD_ATTR_STACKSIZE=_POSIX_THREAD_ATTR_STACKSIZE => 200112L
__need_struct_sigcontext=__need_struct_sigcontext
_CTYPE_SW2=_CTYPE_SW2 => 0x80000000L
_CTYPE_SW0=_CTYPE_SW0 => 0x20000000L
_GLIBCXX_EXTERN_TEMPLATE=_GLIBCXX_EXTERN_TEMPLATE => 1
__APPLE_API_OBSOLETE=__APPLE_API_OBSOLETE
__COPYRIGHT=__COPYRIGHT(s) => __IDSTRING(copyright,s)
putc_unlocked=putc_unlocked(x, fp) => __sputc(x, fp)
__scanflike=__scanflike(fmtarg, firstvararg)
_POSIX_PIPE_BUF=_POSIX_PIPE_BUF => 512
_PC_PATH_MAX=_PC_PATH_MAX => 5
w_termsig=w_termsig => w_T.w_Termsig
__DARWIN_FD_ZERO=__DARWIN_FD_ZERO(p) => bzero(p, sizeof(*(p)))
__STDDEF_H__=__STDDEF_H__
_CS_POSIX_V6_ILP32_OFFBIG_LIBS=_CS_POSIX_V6_ILP32_OFFBIG_LIBS => 7
_POSIX_REALTIME_SIGNALS=_POSIX_REALTIME_SIGNALS => (-1)
_POSIX_THREAD_SPORADIC_SERVER=_POSIX_THREAD_SPORADIC_SERVER => (-1)
SIGSEGV=SIGSEGV => 11
_CS_DARWIN_USER_TEMP_DIR=_CS_DARWIN_USER_TEMP_DIR => 65537
__strftimelike=__strftimelike(fmtarg)
_GLIBCXX_HAVE_SYS_TIME_H=_GLIBCXX_HAVE_SYS_TIME_H => 1
__SMOD=__SMOD => 0x2000
_POSIX_OPEN_MAX=_POSIX_OPEN_MAX => 20
_CTYPE_SWS=_CTYPE_SWS => 30
_XBS5_ILP32_OFF32=_XBS5_ILP32_OFF32 => __ILP32_OFF32
WEOF=WEOF => __DARWIN_WEOF
_GLIBCXX_HAVE_ISINF=_GLIBCXX_HAVE_ISINF => 1
_CTYPE_SWM=_CTYPE_SWM => 0xe0000000L
_V6_LPBIG_OFFBIG=_V6_LPBIG_OFFBIG => __LPBIG_OFFBIG
__glibcxx_requires_valid_range=__glibcxx_requires_valid_range(_First, _Last)
_GLIBCXX_LOCALE=_GLIBCXX_LOCALE => 1
INT16_MAX=INT16_MAX => 32767
_GLIBCXX_BEGIN_NESTED_NAMESPACE=_GLIBCXX_BEGIN_NESTED_NAMESPACE(X, Y) => _GLIBCXX_BEGIN_NAMESPACE(X)
_POSIX_THREAD_PRIO_PROTECT=_POSIX_THREAD_PRIO_PROTECT => (-1)
SIGTTOU=SIGTTOU => 22
PASS_MAX=PASS_MAX => 128
_BSD_I386__TYPES_H_=_BSD_I386__TYPES_H_
_SC_THREAD_THREADS_MAX=_SC_THREAD_THREADS_MAX => 94
_FUNCTEXCEPT_H=_FUNCTEXCEPT_H => 1
_SC_REGEXP=_SC_REGEXP => 77
_GLIBCXX_HAVE_FABSF=_GLIBCXX_HAVE_FABSF => 1
offsetof=offsetof(type, field) => ((size_t)(&((type *)0)->field))
_QUAD_HIGHWORD=_QUAD_HIGHWORD => 1
__need_ucontext_t=__need_ucontext_t
__gthrw_=__gthrw_(name) => name
_OSTREAM_INSERT_H=_OSTREAM_INSERT_H => 1
_POSIX_MEMLOCK_RANGE=_POSIX_MEMLOCK_RANGE => (-1)
_GLIBCXX_VISIBILITY_DEFAULT=_GLIBCXX_VISIBILITY_DEFAULT
_UID_T=_UID_T
__inline=__inline => inline
__DARWIN_OSSwapInt64=__DARWIN_OSSwapInt64(x) => (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
RLIMIT_RSS=RLIMIT_RSS => RLIMIT_AS
_SC_MEMORY_PROTECTION=_SC_MEMORY_PROTECTION => 32
_POSIX_MEMLOCK=_POSIX_MEMLOCK => (-1)
PRIO_MAX=PRIO_MAX => 20
__AVAILABILITY_INTERNAL_WEAK_IMPORT=__AVAILABILITY_INTERNAL_WEAK_IMPORT => __attribute__((weak_import,visibility("default")))
UINT_FAST16_MAX=UINT_FAST16_MAX => UINT16_MAX
_SUSECONDS_T=_SUSECONDS_T
_CS_XBS5_LP64_OFF64_LINTFLAGS=_CS_XBS5_LP64_OFF64_LINTFLAGS => 31
PRIO_PGRP=PRIO_PGRP => 1
UINT32_C=UINT32_C(v) => (v ## U)
_POSIX_ADVISORY_INFO=_POSIX_ADVISORY_INFO => (-1)
_POSIX_LOGIN_NAME_MAX=_POSIX_LOGIN_NAME_MAX => 9
_GLIBCXX_HAVE_SETENV=_GLIBCXX_HAVE_SETENV => 1
_NEW=_NEW
_POSIX_SAVED_IDS=_POSIX_SAVED_IDS => 200112L
putchar_unlocked=putchar_unlocked(x) => putc_unlocked(x, stdout)
_GLIBCXX_CSTDARG=_GLIBCXX_CSTDARG => 1
POLL_MSG=POLL_MSG => 3
FPE_FLTDIV=FPE_FLTDIV => 1
_PTHREAD_MUTEXATTR_T=_PTHREAD_MUTEXATTR_T
fropen=fropen(cookie, fn) => funopen(cookie, fn, 0, 0, 0)
_PC_CASE_SENSITIVE=_PC_CASE_SENSITIVE => 11
_SC_MAPPED_FILES=_SC_MAPPED_FILES => 47
_GLIBCXX_HAVE_SYS_FILIO_H=_GLIBCXX_HAVE_SYS_FILIO_H => 1
_POSIX_MONOTONIC_CLOCK=_POSIX_MONOTONIC_CLOCK => (-1)
_STREAMBUF_ITERATOR_H=_STREAMBUF_ITERATOR_H => 1
_UINTMAX_T=_UINTMAX_T
_SC_COLL_WEIGHTS_MAX=_SC_COLL_WEIGHTS_MAX => 13
__glibcxx_class_requires=__glibcxx_class_requires(_a, _b)
_GLIBCXX_HAVE___BUILTIN_FABSL=_GLIBCXX_HAVE___BUILTIN_FABSL => 1
__SOPT=__SOPT => 0x0400
_GLIBCXX_HAVE___BUILTIN_FABSF=_GLIBCXX_HAVE___BUILTIN_FABSF => 1
_POSIX_RE_DUP_MAX=_POSIX_RE_DUP_MAX => _POSIX2_RE_DUP_MAX
_PC_PIPE_BUF=_PC_PIPE_BUF => 6
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_2_2=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_2_2(x)
__DARWIN_1050=__DARWIN_1050(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_1050)
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_2_1=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_2_1(x)
_PTRDIFF_T=_PTRDIFF_T
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_2_0=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_2_0(x)
__glibcxx_requires_heap=__glibcxx_requires_heap(_First, _Last)
_POSIX_TRACE_SYS_MAX=_POSIX_TRACE_SYS_MAX => 8
BUS_OBJERR=BUS_OBJERR => 3
_INT8_T=_INT8_T
_GLIBCXX_USE_WCHAR_T=_GLIBCXX_USE_WCHAR_T => 1
PTRDIFF_MIN=PTRDIFF_MIN => INT32_MIN
_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS=_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS => 35
POLL_OUT=POLL_OUT => 2
WSTOPPED=WSTOPPED => 0x00000008
PTHREAD_KEYS_MAX=PTHREAD_KEYS_MAX => 512
_WINT_T=_WINT_T
_POSIX_ARG_MAX=_POSIX_ARG_MAX => 4096
__PTHREAD_ONCE_SIZE__=__PTHREAD_ONCE_SIZE__ => 4
_GLIBCXX_HAVE___BUILTIN_ABS=_GLIBCXX_HAVE___BUILTIN_ABS => 1
UINT32_MAX=UINT32_MAX => 4294967295U
_PC_ASYNC_IO=_PC_ASYNC_IO => 17
__DARWIN_SUF_EXTSN=__DARWIN_SUF_EXTSN => "$DARWIN_EXTSN"
_PTHREAD_ONCE_T=_PTHREAD_ONCE_T
PTHREAD_CREATE_DETACHED=PTHREAD_CREATE_DETACHED => 2
SIGEV_SIGNAL=SIGEV_SIGNAL => 1
INT_LEAST8_MIN=INT_LEAST8_MIN => INT8_MIN
_OS__OSBYTEORDER_H=_OS__OSBYTEORDER_H
STDIN_FILENO=STDIN_FILENO => 0
__gthrw2=__gthrw2(name, name2, type)
_MBSTATE_T=_MBSTATE_T
_GLIBCXX_HAVE_TANHL=_GLIBCXX_HAVE_TANHL => 1
__DARWIN_ONLY_64_BIT_INO_T=__DARWIN_ONLY_64_BIT_INO_T => 0
_GLIBCXX_HAVE_TANHF=_GLIBCXX_HAVE_TANHF => 1
_GLIBCXX_CCTYPE=_GLIBCXX_CCTYPE => 1
__SSTR=__SSTR => 0x0200
_POSIX_NO_TRUNC=_POSIX_NO_TRUNC => 200112L
UCHAR_MAX=UCHAR_MAX => 255
_SCHED_H_=_SCHED_H_
__DARWIN_NSIG=__DARWIN_NSIG => 32
FD_COPY=FD_COPY(f, t) => __DARWIN_FD_COPY(f, t)
_CS_PATH=_CS_PATH => 1
_GLIBCXX_HAVE_ASINL=_GLIBCXX_HAVE_ASINL => 1
_SC_2_PBS_MESSAGE=_SC_2_PBS_MESSAGE => 63
_GLIBCXX_HAVE_ASINF=_GLIBCXX_HAVE_ASINF => 1
_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS=_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS => 12
_POSIX2_FORT_RUN=_POSIX2_FORT_RUN => 200112L
_CS_POSIX_V6_LP64_OFF64_LIBS=_CS_POSIX_V6_LP64_OFF64_LIBS => 10
_PID_T=_PID_T
_SC_REALTIME_SIGNALS=_SC_REALTIME_SIGNALS => 36
_PC_SYNC_IO=_PC_SYNC_IO => 25
INT_LEAST32_MAX=INT_LEAST32_MAX => INT32_MAX
_GLIBCXX_USE_C99_INTTYPES_TR1=_GLIBCXX_USE_C99_INTTYPES_TR1 => 1
RUSAGE_SELF=RUSAGE_SELF => 0
_DEV_T=_DEV_T
_PC_AUTH_OPAQUE_NP=_PC_AUTH_OPAQUE_NP => 14
MAX_CANON=MAX_CANON => 1024
_PTHREAD_MUTEX_SIG_init=_PTHREAD_MUTEX_SIG_init => 0x32AAABA7
_XOPEN_VERSION=_XOPEN_VERSION => 600
_CDEFS_H_=_CDEFS_H_
_POSIX2_UPE=_POSIX2_UPE => 200112L
BC_BASE_MAX=BC_BASE_MAX => 99
_POSIX_THREAD_THREADS_MAX=_POSIX_THREAD_THREADS_MAX => 64
_CRMASK=_CRMASK => (~(_CACHED_RUNES - 1))
_POSIX_AIO_MAX=_POSIX_AIO_MAX => 1
_SC_PRIORITIZED_IO=_SC_PRIORITIZED_IO => 34
RLIMIT_AS=RLIMIT_AS => 5
_POSIX_THREAD_ATTR_STACKADDR=_POSIX_THREAD_ATTR_STACKADDR => 200112L
__DARWIN_BYTE_ORDER=__DARWIN_BYTE_ORDER => __DARWIN_LITTLE_ENDIAN
__SIGN=__SIGN => 0x8000
_SC_RE_DUP_MAX=_SC_RE_DUP_MAX => 16
_POSIX2_PBS_CHECKPOINT=_POSIX2_PBS_CHECKPOINT => (-1)
_CS_XBS5_ILP32_OFF32_LINTFLAGS=_CS_XBS5_ILP32_OFF32_LINTFLAGS => 23
__IPHONE_3_2=__IPHONE_3_2 => 30200
_GLIBCXX_HAVE_MMAP=_GLIBCXX_HAVE_MMAP => 1
__IPHONE_3_1=__IPHONE_3_1 => 30100
__IPHONE_3_0=__IPHONE_3_0 => 30000
MB_CUR_MAX=MB_CUR_MAX => __mb_cur_max
__IPHONE_4_0=__IPHONE_4_0 => 40000
_OFF_T=_OFF_T
__IPHONE_4_3=__IPHONE_4_3 => 40300
_SC_CPUTIME=_SC_CPUTIME => 68
__IPHONE_4_1=__IPHONE_4_1 => 40100
__IPHONE_4_2=__IPHONE_4_2 => 40200
_POSIX_TIMEOUTS=_POSIX_TIMEOUTS => (-1)
_GLIBCXX_ATOMIC_BUILTINS=_GLIBCXX_ATOMIC_BUILTINS => 1
SIGTTIN=SIGTTIN => 21
sa_handler=sa_handler => __sigaction_u.__sa_handler
SIGHUP=SIGHUP => 1
_GLIBCXX_HAVE_LIMIT_FSIZE=_GLIBCXX_HAVE_LIMIT_FSIZE => 1
_POSIX_RAW_SOCKETS=_POSIX_RAW_SOCKETS => (-1)
_GLIBCXX_HAVE_SYS_IPC_H=_GLIBCXX_HAVE_SYS_IPC_H => 1
_SC_TRACE_EVENT_FILTER=_SC_TRACE_EVENT_FILTER => 98
_STL_RAW_STORAGE_ITERATOR_H=_STL_RAW_STORAGE_ITERATOR_H => 1
NL_NMAX=NL_NMAX => 1
ru_last=ru_last => ru_nivcsw
_PTHREAD_IMPL_H_=_PTHREAD_IMPL_H_
_SC_SEM_NSEMS_MAX=_SC_SEM_NSEMS_MAX => 49
feof_unlocked=feof_unlocked(p) => __sfeof(p)
__glibcxx_requires_string=__glibcxx_requires_string(_String)
EXIT_SUCCESS=EXIT_SUCCESS => 0
__sferror=__sferror(p) => (((p)->_flags & __SERR) != 0)
CLD_TRAPPED=CLD_TRAPPED => 4
_GLIBCXX_HAVE_S_ISREG=_GLIBCXX_HAVE_S_ISREG => 1
__DARWIN_64_BIT_INO_T=__DARWIN_64_BIT_INO_T => 1
__DARWIN_ONLY_VERS_1050=__DARWIN_ONLY_VERS_1050 => 0
__dead=__dead => __volatile
SA_RESTART=SA_RESTART => 0x0002
NTOHL=NTOHL(x) => (x) = ntohl((__uint32_t)x)
INTMAX_MIN=INTMAX_MIN => INT64_MIN
SCHAR_MAX=SCHAR_MAX => 127
_XBS5_LPBIG_OFFBIG=_XBS5_LPBIG_OFFBIG => __LPBIG_OFFBIG
NTOHS=NTOHS(x) => (x) = ntohs((__uint16_t)x)
W_STOPCODE=W_STOPCODE(sig) => ((sig) << 8 | _WSTOPPED)
_SC_RTSIG_MAX=_SC_RTSIG_MAX => 48
_GLIBCXX_HAVE_UNISTD_H=_GLIBCXX_HAVE_UNISTD_H => 1
SEEK_SET=SEEK_SET => 0
_SC_SS_REPL_MAX=_SC_SS_REPL_MAX => 126
_PC_MAX_INPUT=_PC_MAX_INPUT => 3
__CTERMID_DEFINED=__CTERMID_DEFINED => 1
_CS_XBS5_ILP32_OFFBIG_LDFLAGS=_CS_XBS5_ILP32_OFFBIG_LDFLAGS => 25
__SALC=__SALC => 0x4000
_SC_MEMLOCK=_SC_MEMLOCK => 30
_POSIX_PRIORITY_SCHEDULING=_POSIX_PRIORITY_SCHEDULING => (-1)
__MAC_NA=__MAC_NA => 9999
_DTRACE_CXA_RUNTIME_H=_DTRACE_CXA_RUNTIME_H
WIFSIGNALED=WIFSIGNALED(x) => (_WSTATUS(x) != _WSTOPPED && _WSTATUS(x) != 0)
_SC_FSYNC=_SC_FSYNC => 38
FILENAME_MAX=FILENAME_MAX => 1024
_SC_GETPW_R_SIZE_MAX=_SC_GETPW_R_SIZE_MAX => 71
_DARWIN_FEATURE_64_BIT_INODE=_DARWIN_FEATURE_64_BIT_INODE => 1
__GNUC_LIBSTD_MINOR__=__GNUC_LIBSTD_MINOR__ => 2
PTHREAD_PRIO_INHERIT=PTHREAD_PRIO_INHERIT => 1
_POSIX2_COLL_WEIGHTS_MAX=_POSIX2_COLL_WEIGHTS_MAX => 2
_SC_V6_LP64_OFF64=_SC_V6_LP64_OFF64 => 105
_GLIBCXX_CSTRING=_GLIBCXX_CSTRING => 1
_LIMITS_H_=_LIMITS_H_
_BSD_MACHINE__TYPES_H_=_BSD_MACHINE__TYPES_H_
PTHREAD_PROCESS_PRIVATE=PTHREAD_PROCESS_PRIVATE => 2
_GLIBCXX_HAVE_FABSL=_GLIBCXX_HAVE_FABSL => 1
_STREAMBUF_TCC=_STREAMBUF_TCC => 1
GID_MAX=GID_MAX => 2147483647U
_WPERM_OK=_WPERM_OK => (1<<20)
__APPLE_CC__=__APPLE_CC__ => 1
SIGFPE=SIGFPE => 8
_XBS5_LP64_OFF64=_XBS5_LP64_OFF64 => __LP64_OFF64
_SC_TIMEOUTS=_SC_TIMEOUTS => 95
_GLIBCXX_HAVE_LIBM=_GLIBCXX_HAVE_LIBM => 1
UINTPTR_MAX=UINTPTR_MAX => UINT32_MAX
__MAC_10_3=__MAC_10_3 => 1030
__MAC_10_2=__MAC_10_2 => 1020
_RMFILE_OK=_RMFILE_OK => (1<<14)
__MAC_10_1=__MAC_10_1 => 1010
__MAC_10_0=__MAC_10_0 => 1000
__MAC_10_7=__MAC_10_7 => 1070
_BSD_MACHINE_TYPES_H_=_BSD_MACHINE_TYPES_H_
__MAC_10_6=__MAC_10_6 => 1060
__MAC_10_5=__MAC_10_5 => 1050
__MAC_10_4=__MAC_10_4 => 1040
_GLIBCXX_NUM_FACETS=_GLIBCXX_NUM_FACETS => 28
__need_mcontext_t=__need_mcontext_t
P_tmpdir=P_tmpdir => "/var/tmp/"
_GLIBCXX_HAVE_FINITE=_GLIBCXX_HAVE_FINITE => 1
SI_USER=SI_USER => 0x10001
__DARWIN_EXTSN=__DARWIN_EXTSN(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_EXTSN)
__PTHREAD_RWLOCKATTR_SIZE__=__PTHREAD_RWLOCKATTR_SIZE__ => 12
TMP_MAX=TMP_MAX => 308915776
__DARWIN_OSSwapConstInt32=__DARWIN_OSSwapConstInt32(x) => ((__uint32_t)((((__uint32_t)(x) & 0xff000000) >> 24) | (((__uint32_t)(x) & 0x00ff0000) >> 8) | (((__uint32_t)(x) & 0x0000ff00) << 8) | (((__uint32_t)(x) & 0x000000ff) << 24)))
SIG_IGN=SIG_IGN => (void (*)(int))1
WTERMSIG=WTERMSIG(x) => (_WSTATUS(x))
ILL_ILLOPN=ILL_ILLOPN => 4
_GLIBCXX_HAVE___BUILTIN_COS=_GLIBCXX_HAVE___BUILTIN_COS => 1
_SC_MEMLOCK_RANGE=_SC_MEMLOCK_RANGE => 31
_ITERATOR_H=_ITERATOR_H => 1
PTHREAD_STACK_MIN=PTHREAD_STACK_MIN => 8192
_SC_RAW_SOCKETS=_SC_RAW_SOCKETS => 119
_OSTREAM_TCC=_OSTREAM_TCC => 1
UINT16_MAX=UINT16_MAX => 65535
_GLIBCXX_HAVE___BUILTIN_SIN=_GLIBCXX_HAVE___BUILTIN_SIN => 1
ULLONG_MAX=ULLONG_MAX => 0xffffffffffffffffULL
ILL_ILLOPC=ILL_ILLOPC => 1
_POSIX_V7_LPBIG_OFFBIG=_POSIX_V7_LPBIG_OFFBIG => __LPBIG_OFFBIG
_STL_HEAP_H=_STL_HEAP_H => 1
SA_NODEFER=SA_NODEFER => 0x0010
__GNUC__=__GNUC__ => 1
_GLIBCXX_HAVE___BUILTIN_COSL=_GLIBCXX_HAVE___BUILTIN_COSL => 1
_POSIX_SYMLOOP_MAX=_POSIX_SYMLOOP_MAX => 8
SEGV_ACCERR=SEGV_ACCERR => 2
_POSIX2_EXPR_NEST_MAX=_POSIX2_EXPR_NEST_MAX => 32
L_tmpnam=L_tmpnam => 1024
_LOCALE_H_=_LOCALE_H_
UINT_LEAST16_MAX=UINT_LEAST16_MAX => UINT16_MAX
_GLIBCXX_HAVE___BUILTIN_COSF=_GLIBCXX_HAVE___BUILTIN_COSF => 1
_SC_SAVED_IDS=_SC_SAVED_IDS => 7
_GLIBCXX_HAVE_MODFL=_GLIBCXX_HAVE_MODFL => 1
_GLIBCXX_DEBUG_MACRO_SWITCH_H=_GLIBCXX_DEBUG_MACRO_SWITCH_H => 1
UINT8_C=UINT8_C(v) => (v ## U)
_GLIBCXX_HAVE_VSWSCANF=_GLIBCXX_HAVE_VSWSCANF => 1
SIG_BLOCK=SIG_BLOCK => 1
_GLIBCXX_DEBUG_PEDASSERT=_GLIBCXX_DEBUG_PEDASSERT(_Condition)
SV_NODEFER=SV_NODEFER => SA_NODEFER
_ALLOCATOR_H=_ALLOCATOR_H => 1
__DARWIN_NBBY=__DARWIN_NBBY => 8
__glibcxx_requires_cond=__glibcxx_requires_cond(_Cond, _Msg)
ACCESSX_MAX_DESCRIPTORS=ACCESSX_MAX_DESCRIPTORS => 100
_GLIBCXX_HAVE_MODFF=_GLIBCXX_HAVE_MODFF => 1
LC_COLLATE=LC_COLLATE => 1
F_OK=F_OK => 0
_XOPEN_LEGACY=_XOPEN_LEGACY => (-1)
UINT64_MAX=UINT64_MAX => 18446744073709551615ULL
_GLIBCXX_HAVE_TANF=_GLIBCXX_HAVE_TANF => 1
_GLIBCXX_HAVE_WCHAR_H=_GLIBCXX_HAVE_WCHAR_H => 1
NGROUPS_MAX=NGROUPS_MAX => 16
_POSIX2_PBS_LOCATE=_POSIX2_PBS_LOCATE => (-1)
_POSIX2_PBS=_POSIX2_PBS => (-1)
__SAPP=__SAPP => 0x0100
SA_SIGINFO=SA_SIGINFO => 0x0040
INTMAX_C=INTMAX_C(v) => (v ## LL)
_GLIBCXX_HAVE_TANL=_GLIBCXX_HAVE_TANL => 1
_CLOCK_T=_CLOCK_T
w_stopsig=w_stopsig => w_S.w_Stopsig
PTHREAD_CANCELED=PTHREAD_CANCELED => ((void *) 1)
PRIO_DARWIN_BG=PRIO_DARWIN_BG => 0x1000
_GLIBXX_STREAMBUF=_GLIBXX_STREAMBUF => 1
_STL_UNINITIALIZED_H=_STL_UNINITIALIZED_H => 1
_GLIBCXX_HAVE_SYS_SEM_H=_GLIBCXX_HAVE_SYS_SEM_H => 1
PRIO_PROCESS=PRIO_PROCESS => 0
__DARWIN_ONLY_UNIX_CONFORMANCE=__DARWIN_ONLY_UNIX_CONFORMANCE => 0
_PC_2_SYMLINKS=_PC_2_SYMLINKS => 15
INT64_MAX=INT64_MAX => 9223372036854775807LL
_INTMAX_T=_INTMAX_T
fileno_unlocked=fileno_unlocked(p) => __sfileno(p)
HTONL=HTONL(x) => (x) = htonl((__uint32_t)x)
_XOPEN_REALTIME=_XOPEN_REALTIME => (-1)
LC_CTYPE=LC_CTYPE => 2
SS_DISABLE=SS_DISABLE => 0x0004
_PC_REC_MAX_XFER_SIZE=_PC_REC_MAX_XFER_SIZE => 21
WSTOPSIG=WSTOPSIG(x) => (_W_INT(x) >> 8)
NL_LANGMAX=NL_LANGMAX => 14
_GLIBCXX_HAVE_LOGF=_GLIBCXX_HAVE_LOGF => 1
_SC_2_UPE=_SC_2_UPE => 25
HTONS=HTONS(x) => (x) = htons((__uint16_t)x)
__DARWIN_OSSwapConstInt64=__DARWIN_OSSwapConstInt64(x) => ((__uint64_t)((((__uint64_t)(x) & 0xff00000000000000ULL) >> 56) | (((__uint64_t)(x) & 0x00ff000000000000ULL) >> 40) | (((__uint64_t)(x) & 0x0000ff0000000000ULL) >> 24) | (((__uint64_t)(x) & 0x000000ff00000000ULL) >> 8) | (((__uint64_t)(x) & 0x00000000ff000000ULL) << 8) | (((__uint64_t)(x) & 0x0000000000ff0000ULL) << 24) | (((__uint64_t)(x) & 0x000000000000ff00ULL) << 40) | (((__uint64_t)(x) & 0x00000000000000ffULL) << 56)))
LC_ALL=LC_ALL => 0
_PC_CASE_PRESERVING=_PC_CASE_PRESERVING => 12
_GLIBCXX_HAVE_LOGL=_GLIBCXX_HAVE_LOGL => 1
CXA_RUNTIME_CXA_EXCEPTION_RETHROW_ENABLED=CXA_RUNTIME_CXA_EXCEPTION_RETHROW_ENABLED() => __dtrace_isenabled$cxa_runtime$cxa_exception_rethrow$v1()
_GLIBCXX_HAVE_FLOORF=_GLIBCXX_HAVE_FLOORF => 1
_GLIBCXX_HAVE_FLOORL=_GLIBCXX_HAVE_FLOORL => 1
_GLIBCXX_CSTDDEF=_GLIBCXX_CSTDDEF => 1
_GLIBCXX_HAVE_ACOSF=_GLIBCXX_HAVE_ACOSF => 1
PTHREAD_MUTEX_DEFAULT=PTHREAD_MUTEX_DEFAULT => PTHREAD_MUTEX_NORMAL
UINT_MAX=UINT_MAX => 0xffffffff
_GLIBCXX_HAVE_ACOSL=_GLIBCXX_HAVE_ACOSL => 1
__ILP32_OFFBIG=__ILP32_OFFBIG => (1)
_SC_STREAM_MAX=_SC_STREAM_MAX => 26
CXA_RUNTIME_CXA_EXCEPTION_RETHROW=CXA_RUNTIME_CXA_EXCEPTION_RETHROW() => do { __asm__ volatile(".reference " CXA_RUNTIME_TYPEDEFS); __dtrace_probe$cxa_runtime$cxa_exception_rethrow$v1(); __asm__ volatile(".reference " CXA_RUNTIME_STABILITY); } while (0)
PTHREAD_PRIO_PROTECT=PTHREAD_PRIO_PROTECT => 2
PTHREAD_CANCEL_ENABLE=PTHREAD_CANCEL_ENABLE => 0x01
IOPOL_NORMAL=IOPOL_NORMAL => 1
_CS_POSIX_V6_ILP32_OFF32_LIBS=_CS_POSIX_V6_ILP32_OFF32_LIBS => 4
_GLIBCXX_HAVE_FMODF=_GLIBCXX_HAVE_FMODF => 1
WNOHANG=WNOHANG => 0x00000001
_STDINT_H_=_STDINT_H_
_W_INT=_W_INT(w) => (*(int *)&(w))
POLL_IN=POLL_IN => 1
SCHAR_MIN=SCHAR_MIN => (-128)
_GLIBCXX_STD=_GLIBCXX_STD => std
_GLIBCXX_MEMORY=_GLIBCXX_MEMORY => 1
SIGBUS=SIGBUS => 10
_PTHREAD_MUTEX_T=_PTHREAD_MUTEX_T
pthread_cleanup_push=pthread_cleanup_push(func, val) => { struct __darwin_pthread_handler_rec __handler; pthread_t __self = pthread_self(); __handler.__routine = func; __handler.__arg = val; __handler.__next = __self->__cleanup_stack; __self->__cleanup_stack = &__handler;
_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS=_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS => 14
_GLIBCXX_HAVE_FMODL=_GLIBCXX_HAVE_FMODL => 1
_SC_XBS5_ILP32_OFF32=_SC_XBS5_ILP32_OFF32 => 122
_SYS__SELECT_H_=_SYS__SELECT_H_
__RCSID=__RCSID(s) => __IDSTRING(rcsid,s)
_CTYPE_H_=_CTYPE_H_
_LC_LAST=_LC_LAST => 7
UINT16_C=UINT16_C(v) => (v ## U)
_CS_XBS5_ILP32_OFFBIG_CFLAGS=_CS_XBS5_ILP32_OFFBIG_CFLAGS => 24
_GLIBCXX_IOSTREAM=_GLIBCXX_IOSTREAM => 1
_POSIX_TRACE_INHERIT=_POSIX_TRACE_INHERIT => (-1)
WEXITSTATUS=WEXITSTATUS(x) => ((_W_INT(x) >> 8) & 0x000000ff)
__PTHREAD_COND_SIZE__=__PTHREAD_COND_SIZE__ => 24
_GLIBCXX_HAVE_FLOAT_H=_GLIBCXX_HAVE_FLOAT_H => 1
SIGQUIT=SIGQUIT => 3
_WATTR_OK=_WATTR_OK => (1<<16)
_POSIX_LINK_MAX=_POSIX_LINK_MAX => 8
_SC_2_PBS_CHECKPOINT=_SC_2_PBS_CHECKPOINT => 61
__AVAILABILITY_INTERNAL_REGULAR=__AVAILABILITY_INTERNAL_REGULAR => __attribute__((visibility("default")))
__DARWIN_OS_INLINE=__DARWIN_OS_INLINE => static inline
_UINT32_T=_UINT32_T
__SOFF=__SOFF => 0x1000
SIGTRAP=SIGTRAP => 5
_POSIX_SIGQUEUE_MAX=_POSIX_SIGQUEUE_MAX => 32
INT_FAST8_MIN=INT_FAST8_MIN => INT8_MIN
_SC_ASYNCHRONOUS_IO=_SC_ASYNCHRONOUS_IO => 28
SIGPROF=SIGPROF => 27
PTHREAD_EXPLICIT_SCHED=PTHREAD_EXPLICIT_SCHED => 2
_GLIBCXX_END_NAMESPACE=_GLIBCXX_END_NAMESPACE => }
_GLIBCXX_HAVE___BUILTIN_SQRT=_GLIBCXX_HAVE___BUILTIN_SQRT => 1
_GLIBCXX_BEGIN_NAMESPACE=_GLIBCXX_BEGIN_NAMESPACE(X) => namespace X _GLIBCXX_VISIBILITY_DEFAULT {
USHRT_MAX=USHRT_MAX => 65535
SIGWINCH=SIGWINCH => 28
LLONG_MAX=LLONG_MAX => 0x7fffffffffffffffLL
NULL=NULL => __DARWIN_NULL
_WCTRANS_T=_WCTRANS_T
_POSIX2_EQUIV_CLASS_MAX=_POSIX2_EQUIV_CLASS_MAX => 2
__glibcxx_requires_partitioned_pred=__glibcxx_requires_partitioned_pred(_First, _Last, _Value, _Pred)
__END_DECLS=__END_DECLS => }
_CS_DARWIN_USER_CACHE_DIR=_CS_DARWIN_USER_CACHE_DIR => 65538
_GLIBCXX_HAVE_MACHINE_ENDIAN_H=_GLIBCXX_HAVE_MACHINE_ENDIAN_H => 1
_SC_BC_SCALE_MAX=_SC_BC_SCALE_MAX => 11
_GLIBCXX_USE_C99_COMPLEX=_GLIBCXX_USE_C99_COMPLEX => 1
_GLIBCXX_CWCTYPE=_GLIBCXX_CWCTYPE => 1
_SC_READER_WRITER_LOCKS=_SC_READER_WRITER_LOCKS => 76
_M_I86=_M_I86 => 1
RLIM_SAVED_MAX=RLIM_SAVED_MAX => RLIM_INFINITY
_SC_TTY_NAME_MAX=_SC_TTY_NAME_MAX => 101
__DARWIN_OSSwapConstInt16=__DARWIN_OSSwapConstInt16(x) => ((__uint16_t)((((__uint16_t)(x) & 0xff00) >> 8) | (((__uint16_t)(x) & 0x00ff) << 8)))
_GLIBCXX_HAVE_GETIPINFO=_GLIBCXX_HAVE_GETIPINFO => 1
IOPOL_THROTTLE=IOPOL_THROTTLE => 3
_POSIX_SHARED_MEMORY_OBJECTS=_POSIX_SHARED_MEMORY_OBJECTS => (-1)
__DARWIN_SUF_64_BIT_INO_T=__DARWIN_SUF_64_BIT_INO_T => "$INODE64"
_PTHREAD_ATTR_T=_PTHREAD_ATTR_T
IOPOL_SCOPE_PROCESS=IOPOL_SCOPE_PROCESS => 0
__SMBF=__SMBF => 0x0080
IOPOL_SCOPE_THREAD=IOPOL_SCOPE_THREAD => 1
_SC_ATEXIT_MAX=_SC_ATEXIT_MAX => 107
_GLIBCXX_USE_LONG_LONG=_GLIBCXX_USE_LONG_LONG => 1
BUFSIZ=BUFSIZ => 1024
BUS_NOOP=BUS_NOOP => 0
WAIT_MYPGRP=WAIT_MYPGRP => 0
_GLIBCXX_HAVE___BUILTIN_SQRTL=_GLIBCXX_HAVE___BUILTIN_SQRTL => 1
__P=__P(protos) => protos
WIFSTOPPED=WIFSTOPPED(x) => (_WSTATUS(x) == _WSTOPPED && WSTOPSIG(x) != 0x13)
SA_NOCLDWAIT=SA_NOCLDWAIT => 0x0020
_POSIX_SHELL=_POSIX_SHELL => 200112L
__printflike=__printflike(fmtarg, firstvararg)
_SC_TRACE_SYS_MAX=_SC_TRACE_SYS_MAX => 129
_GLIBCXX_HAVE_ISWBLANK=_GLIBCXX_HAVE_ISWBLANK => 1
_SC_AIO_MAX=_SC_AIO_MAX => 43
_POSIX_SEM_NSEMS_MAX=_POSIX_SEM_NSEMS_MAX => 256
__APPLE_API_UNSTABLE=__APPLE_API_UNSTABLE
_SC_VERSION=_SC_VERSION => 8
_TR1_CSTDARG=_TR1_CSTDARG => 1
_GLIBCXX_CLIMITS=_GLIBCXX_CLIMITS => 1
__CONCAT=__CONCAT(x, y) => x ## y
_V6_LP64_OFF64=_V6_LP64_OFF64 => __LP64_OFF64
__DARWIN_SUF_UNIX03=__DARWIN_SUF_UNIX03 => "$UNIX2003"
__SWR=__SWR => 0x0008
SA_USERSPACE_MASK=SA_USERSPACE_MASK => (SA_ONSTACK | SA_RESTART | SA_RESETHAND | SA_NOCLDSTOP | SA_NODEFER | SA_NOCLDWAIT | SA_SIGINFO)
_SC_SEM_VALUE_MAX=_SC_SEM_VALUE_MAX => 50
__OSX_AVAILABLE_BUT_DEPRECATED=__OSX_AVAILABLE_BUT_DEPRECATED(_macIntro, _macDep, _iphoneIntro, _iphoneDep)
__DARWIN_PDP_ENDIAN=__DARWIN_PDP_ENDIAN => 3412
clearerr_unlocked=clearerr_unlocked(p) => __sclearerr(p)
_SC_HOST_NAME_MAX=_SC_HOST_NAME_MAX => 72
_CS_XBS5_ILP32_OFFBIG_LIBS=_CS_XBS5_ILP32_OFFBIG_LIBS => 26
SV_INTERRUPT=SV_INTERRUPT => SA_RESTART
__N=__N(msgid) => (msgid)
_GLIBCXX_HAVE___BUILTIN_SQRTF=_GLIBCXX_HAVE___BUILTIN_SQRTF => 1
_GLIBCXX_HAVE_STRING_H=_GLIBCXX_HAVE_STRING_H => 1
_UINT8_T=_UINT8_T
_PTHREAD_RWLOCK_SIG_init=_PTHREAD_RWLOCK_SIG_init => 0x2DA8B3B4
_XOPEN_XCU_VERSION=_XOPEN_XCU_VERSION => 4
_SC_LINE_MAX=_SC_LINE_MAX => 15
__STRING=__STRING(x) => #x
__APPLE_API_PRIVATE=__APPLE_API_PRIVATE
_ID_T=_ID_T
_PTHREAD_ERRORCHECK_MUTEX_SIG_init=_PTHREAD_ERRORCHECK_MUTEX_SIG_init => 0x32AAABA1
_GLIBCXX_HAVE_SYS_STAT_H=_GLIBCXX_HAVE_SYS_STAT_H => 1
_STL_CONSTRUCT_H=_STL_CONSTRUCT_H => 1
_POSIX_CLOCK_SELECTION=_POSIX_CLOCK_SELECTION => (-1)
_GLIBCXX_HAVE_SYS_TYPES_H=_GLIBCXX_HAVE_SYS_TYPES_H => 1
_POSIX_STREAM_MAX=_POSIX_STREAM_MAX => 8
__FILE__=__FILE__
_POSIX_NAME_MAX=_POSIX_NAME_MAX => 14
UINT_LEAST32_MAX=UINT_LEAST32_MAX => UINT32_MAX
_SC_THREAD_ATTR_STACKSIZE=_SC_THREAD_ATTR_STACKSIZE => 83
_SC_THREAD_STACK_MIN=_SC_THREAD_STACK_MIN => 93
_POSIX_IPV6=_POSIX_IPV6 => 200112L
__LOCALE_H_=__LOCALE_H_
__WCTYPE_H_=__WCTYPE_H_
_C_IO_STDIO_H=_C_IO_STDIO_H => 1
_SC_AIO_PRIO_DELTA_MAX=_SC_AIO_PRIO_DELTA_MAX => 44
_POSIX2_C_DEV=_POSIX2_C_DEV => 200112L
stderr=stderr => __stderrp
__i386__=__i386__ => 1
PTHREAD_CANCEL_DEFERRED=PTHREAD_CANCEL_DEFERRED => 0x02
__DARWIN_1050ALIAS=__DARWIN_1050ALIAS(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_1050 __DARWIN_SUF_UNIX03)
_GLIBCXX_HAVE_STRINGS_H=_GLIBCXX_HAVE_STRINGS_H => 1
_GLIBCXX_HAVE_LIMIT_AS=_GLIBCXX_HAVE_LIMIT_AS => 1
PTHREAD_MUTEX_INITIALIZER=PTHREAD_MUTEX_INITIALIZER => {_PTHREAD_MUTEX_SIG_init, {0}}
_GLIBCXX_GTHREAD_USE_WEAK=_GLIBCXX_GTHREAD_USE_WEAK => 0
___POSIX_C_DEPRECATED_STARTING_199506L=___POSIX_C_DEPRECATED_STARTING_199506L
PRIO_DARWIN_THREAD=PRIO_DARWIN_THREAD => 3
_EXT_TYPE_TRAITS=_EXT_TYPE_TRAITS => 1
PATH_MAX=PATH_MAX => 1024
SIG_ERR=SIG_ERR => ((void (*)(int))-1)
SCHED_FIFO=SCHED_FIFO => 4
INT64_MIN=INT64_MIN => (-INT64_MAX-1)
_GLIBCXX_HAVE_STDBOOL_H=_GLIBCXX_HAVE_STDBOOL_H => 1
__PTHREAD_RWLOCK_SIZE__=__PTHREAD_RWLOCK_SIZE__ => 124
_POSIX_VDISABLE=_POSIX_VDISABLE => ((unsigned char)'\377')
_STL_RELOPS_H=_STL_RELOPS_H => 1
_CTYPE_D=_CTYPE_D => 0x00000400L
_CTYPE_C=_CTYPE_C => 0x00000200L
_POSIX_REGEXP=_POSIX_REGEXP => 200112L
_CTYPE_B=_CTYPE_B => 0x00020000L
_CTYPE_A=_CTYPE_A => 0x00000100L
_GLIBCXX_ATOMICITY_H=_GLIBCXX_ATOMICITY_H => 1
_SYS_SIGNAL_H_=_SYS_SIGNAL_H_
_CTYPE_G=_CTYPE_G => 0x00000800L
_SC_THREAD_PROCESS_SHARED=_SC_THREAD_PROCESS_SHARED => 90
_GLIBCXX_USE_C99_CTYPE_TR1=_GLIBCXX_USE_C99_CTYPE_TR1 => 1
__SYS_APPLEAPIOPTS_H__=__SYS_APPLEAPIOPTS_H__
NL_MSGMAX=NL_MSGMAX => 32767
_POSIX2_SW_DEV=_POSIX2_SW_DEV => 200112L
_CTYPE_L=_CTYPE_L => 0x00001000L
_CTYPE_I=_CTYPE_I => 0x00080000L
SEEK_CUR=SEEK_CUR => 1
_CTYPE_P=_CTYPE_P => 0x00002000L
__DARWIN_1050INODE64=__DARWIN_1050INODE64(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_1050 __DARWIN_SUF_64_BIT_INO_T)
W_EXITCODE=W_EXITCODE(ret, sig) => ((ret) << 8 | (sig))
_SC_PAGE_SIZE=_SC_PAGE_SIZE => _SC_PAGESIZE
TRAP_TRACE=TRAP_TRACE => 2
_CTYPE_S=_CTYPE_S => 0x00004000L
_CS_DARWIN_USER_DIR=_CS_DARWIN_USER_DIR => 65536
_STRINGFWD_H=_STRINGFWD_H => 1
_CTYPE_T=_CTYPE_T => 0x00100000L
_FUNCTION_H=_FUNCTION_H => 1
_CTYPE_Q=_CTYPE_Q => 0x00200000L
_CTYPE_R=_CTYPE_R => 0x00040000L
_CTYPE_X=_CTYPE_X => 0x00010000L
_CTYPE_U=_CTYPE_U => 0x00008000L
_REXT_OK=_REXT_OK => (1<<17)
PTHREAD_ERRORCHECK_MUTEX_INITIALIZER=PTHREAD_ERRORCHECK_MUTEX_INITIALIZER => {_PTHREAD_ERRORCHECK_MUTEX_SIG_init, {0}}
_WEXT_OK=_WEXT_OK => (1<<18)
NSIG=NSIG => __DARWIN_NSIG
SA_ONSTACK=SA_ONSTACK => 0x0001
STDOUT_FILENO=STDOUT_FILENO => 1
_SC_2_LOCALEDEF=_SC_2_LOCALEDEF => 23
_XOPEN_NAME_MAX=_XOPEN_NAME_MAX => 255
_SC_TRACE_EVENT_NAME_MAX=_SC_TRACE_EVENT_NAME_MAX => 127
PTHREAD_MUTEX_RECURSIVE=PTHREAD_MUTEX_RECURSIVE => 2
__LITTLE_ENDIAN__=__LITTLE_ENDIAN__ => 1
__DARWIN_WCHAR_MAX=__DARWIN_WCHAR_MAX => 0x7fffffff
SCHED_RR=SCHED_RR => 2
_SC_ADVISORY_INFO=_SC_ADVISORY_INFO => 65
_tolower=_tolower(c) => __tolower(c)
_XOPEN_PATH_MAX=_XOPEN_PATH_MAX => 1024
LLONG_MIN=LLONG_MIN => (-0x7fffffffffffffffLL-1)
__EXCEPTION__=__EXCEPTION__
__CAST_AWAY_QUALIFIER=__CAST_AWAY_QUALIFIER(variable, qualifier, type) => (type) (long)(variable)
_POSIX2_RE_DUP_MAX=_POSIX2_RE_DUP_MAX => 255
_POSIX2_BC_SCALE_MAX=_POSIX2_BC_SCALE_MAX => 99
INT_FAST64_MIN=INT_FAST64_MIN => INT64_MIN
_DELETE_OK=_DELETE_OK => (1<<12)
_PC_FILESIZEBITS=_PC_FILESIZEBITS => 18
EOF=EOF => (-1)
_SC_TIMERS=_SC_TIMERS => 41
__DARWIN_CTYPE_TOP_static_inline=__DARWIN_CTYPE_TOP_static_inline => static __inline
_PC_ALLOC_SIZE_MIN=_PC_ALLOC_SIZE_MIN => 16
PTHREAD_MUTEX_ERRORCHECK=PTHREAD_MUTEX_ERRORCHECK => 1
WINT_MAX=WINT_MAX => INT32_MAX
INT_FAST8_MAX=INT_FAST8_MAX => INT8_MAX
__DARWIN_C_LEVEL=__DARWIN_C_LEVEL => __DARWIN_C_FULL
_GLIBCXX_IOS=_GLIBCXX_IOS => 1
_TIME_H_=_TIME_H_
F_ULOCK=F_ULOCK => 0
_POSIX_CHILD_MAX=_POSIX_CHILD_MAX => 25
_SC_PAGESIZE=_SC_PAGESIZE => 29
_MACH_PORT_T=_MACH_PORT_T
WCHAR_MIN=WCHAR_MIN => __DARWIN_WCHAR_MIN
_GLIBCXX_ALGORITHM=_GLIBCXX_ALGORITHM => 1
__const=__const => const
sa_sigaction=sa_sigaction => __sigaction_u.__sa_sigaction
_GLIBCXX_HAVE_STDLIB_H=_GLIBCXX_HAVE_STDLIB_H => 1
SIZE_MAX=SIZE_MAX => UINT32_MAX
_GLIBCXX_HAVE___BUILTIN_FABS=_GLIBCXX_HAVE___BUILTIN_FABS => 1
EXIT_FAILURE=EXIT_FAILURE => 1
WAIT_ANY=WAIT_ANY => (-1)
_CS_POSIX_V6_ILP32_OFF32_LDFLAGS=_CS_POSIX_V6_ILP32_OFF32_LDFLAGS => 3
getc_unlocked=getc_unlocked(fp) => __sgetc(fp)
CLD_NOOP=CLD_NOOP => 0
__POSIX_C_DEPRECATED=__POSIX_C_DEPRECATED(ver) => ___POSIX_C_DEPRECATED_STARTING_ ## ver
sv_onstack=sv_onstack => sv_flags
CXA_RUNTIME_CXA_EXCEPTION_THROW_ENABLED=CXA_RUNTIME_CXA_EXCEPTION_THROW_ENABLED() => __dtrace_isenabled$cxa_runtime$cxa_exception_throw$v1()
RLIMIT_NPROC=RLIMIT_NPROC => 7
COLL_WEIGHTS_MAX=COLL_WEIGHTS_MAX => 2
W_OK=W_OK => (1<<1)
_CS_XBS5_LPBIG_OFFBIG_LDFLAGS=_CS_XBS5_LPBIG_OFFBIG_LDFLAGS => 33
try=try => if (true)
__DARWIN_UNIX03=__DARWIN_UNIX03 => 1
_POSIX_TRACE_LOG=_POSIX_TRACE_LOG => (-1)
__BEGIN_DECLS=__BEGIN_DECLS => extern "C" {
_SC_THREAD_ATTR_STACKADDR=_SC_THREAD_ATTR_STACKADDR => 82
_GLIBCXX_GCC_GTHR_POSIX_H=_GLIBCXX_GCC_GTHR_POSIX_H
FPE_FLTSUB=FPE_FLTSUB => 6
_USECONDS_T=_USECONDS_T
SHRT_MIN=SHRT_MIN => (-32768)
_POSIX_V6_LPBIG_OFFBIG=_POSIX_V6_LPBIG_OFFBIG => __LPBIG_OFFBIG
TARGET_CPU_X86_64=TARGET_CPU_X86_64 => 1
BC_SCALE_MAX=BC_SCALE_MAX => 99
__DARWIN_C_ANSI=__DARWIN_C_ANSI => 010000L
__DARWIN_LDBL_COMPAT2=__DARWIN_LDBL_COMPAT2(x)
_POSIX2_C_BIND=_POSIX2_C_BIND => 200112L
_GLIBCXX_HAVE_FENV_H=_GLIBCXX_HAVE_FENV_H => 1
_BASIC_STRING_H=_BASIC_STRING_H => 1
NL_ARGMAX=NL_ARGMAX => 9
__APPLE_API_STABLE=__APPLE_API_STABLE
WNOWAIT=WNOWAIT => 0x00000020
FOPEN_MAX=FOPEN_MAX => 20
PIPE_BUF=PIPE_BUF => 512
__DARWIN_LONG_DOUBLE_IS_DOUBLE=__DARWIN_LONG_DOUBLE_IS_DOUBLE => 0
_GLIBCXX_HAVE___BUILTIN_LABS=_GLIBCXX_HAVE___BUILTIN_LABS => 1
_GLIBCXX_SYMVER_DARWIN=_GLIBCXX_SYMVER_DARWIN => 1
_GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY=_GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY => 1
_POSIX_PATH_MAX=_POSIX_PATH_MAX => 256
RAND_MAX=RAND_MAX => 0x7fffffff
_XBS5_ILP32_OFFBIG=_XBS5_ILP32_OFFBIG => __ILP32_OFFBIG
__ILP32_OFF32=__ILP32_OFF32 => (-1)
__need_struct_timespec=__need_struct_timespec
_ALGO_H=_ALGO_H => 1
WUNTRACED=WUNTRACED => 0x00000002
SV_NOCLDSTOP=SV_NOCLDSTOP => SA_NOCLDSTOP
__GXX_MERGED_TYPEINFO_NAMES=__GXX_MERGED_TYPEINFO_NAMES => 0
__glibcxx_requires_heap_pred=__glibcxx_requires_heap_pred(_First, _Last, _Pred)
_GLIBCXX_HAVE_VFWSCANF=_GLIBCXX_HAVE_VFWSCANF => 1
SIGALRM=SIGALRM => 14
_PC_PRIO_IO=_PC_PRIO_IO => 19
RLIM_INFINITY=RLIM_INFINITY => (((__uint64_t)1 << 63) - 1)
CHAR_BIT=CHAR_BIT => 8
__APPLE_CPP__=__APPLE_CPP__ => 1
__DARWIN_WEOF=__DARWIN_WEOF => ((__darwin_wint_t)-1)
_STRUCT_TIMEVAL=_STRUCT_TIMEVAL => struct timeval
_GLIBCXX_HAVE_COPYSIGN=_GLIBCXX_HAVE_COPYSIGN => 1
MB_LEN_MAX=MB_LEN_MAX => 6
_SC_XOPEN_UNIX=_SC_XOPEN_UNIX => 115
__DARWIN_SUF_NON_CANCELABLE=__DARWIN_SUF_NON_CANCELABLE
__glibcxx_integral_traps=__glibcxx_integral_traps => true
_MODE_T=_MODE_T
_SYS_RESOURCE_H_=_SYS_RESOURCE_H_
SI_QUEUE=SI_QUEUE => 0x10002
__need_struct_timeval=__need_struct_timeval
__throw_exception_again=__throw_exception_again
__DARWIN_NO_LONG_LONG=__DARWIN_NO_LONG_LONG => (defined(__STRICT_ANSI__) && (__STDC_VERSION__-0 < 199901L) && !defined(__GNUG__))
CXA_RUNTIME_TYPEDEFS=CXA_RUNTIME_TYPEDEFS => "___dtrace_typedefs$cxa_runtime$v2"
__SLBF=__SLBF => 0x0001
_POSIX2_VERSION=_POSIX2_VERSION => 200112L
SIGEV_THREAD=SIGEV_THREAD => 3
_POSIX_FSYNC=_POSIX_FSYNC => 200112L
_INTPTR_T=_INTPTR_T
_RUNE_MAGIC_A=_RUNE_MAGIC_A => "RuneMagA"
PTHREAD_MUTEX_NORMAL=PTHREAD_MUTEX_NORMAL => 0
_PC_SYMLINK_MAX=_PC_SYMLINK_MAX => 24
_POSIX2_CHAR_TERM=_POSIX2_CHAR_TERM => 200112L
__strfmonlike=__strfmonlike(fmtarg, firstvararg)
SIGTSTP=SIGTSTP => 18
INT16_C=INT16_C(v) => (v)
_POSIX2_BC_STRING_MAX=_POSIX2_BC_STRING_MAX => 1000
htonl=htonl(x) => __DARWIN_OSSwapInt32(x)
CLD_DUMPED=CLD_DUMPED => 3
_XOPEN_CRYPT=_XOPEN_CRYPT => (1)
_BSD_MACHINE_SIGNAL_H_=_BSD_MACHINE_SIGNAL_H_
_SC_NPROCESSORS_CONF=_SC_NPROCESSORS_CONF => 57
htons=htons(x) => __DARWIN_OSSwapInt16(x)
OPEN_MAX=OPEN_MAX => 10240
_PTHREAD_RWLOCK_T=_PTHREAD_RWLOCK_T
_SC_2_C_BIND=_SC_2_C_BIND => 18
_SC_2_FORT_DEV=_SC_2_FORT_DEV => 21
INT_MIN=INT_MIN => (-2147483647-1)
__DARWIN_ALIAS_I=__DARWIN_ALIAS_I(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_64_BIT_INO_T __DARWIN_SUF_UNIX03)
_SC_XOPEN_CRYPT=_SC_XOPEN_CRYPT => 108
__DARWIN_NFDBITS=__DARWIN_NFDBITS => (sizeof(__int32_t) * __DARWIN_NBBY)
_GLIBCXX_OSTREAM=_GLIBCXX_OSTREAM => 1
_SC_2_SW_DEV=_SC_2_SW_DEV => 24
SIG_DFL=SIG_DFL => (void (*)(int))0
UINTMAX_C=UINTMAX_C(v) => (v ## ULL)
_GLIBCXX_PTRDIFF_T_IS_INT=_GLIBCXX_PTRDIFF_T_IS_INT => 1
_STDIO_H_=_STDIO_H_
CLOCKS_PER_SEC=CLOCKS_PER_SEC => 1000000
_SC_2_PBS_LOCATE=_SC_2_PBS_LOCATE => 62
__SRD=__SRD => 0x0004
_IOS_BASE_H=_IOS_BASE_H => 1
stdout=stdout => __stdoutp
_LOCALE_FWD_H=_LOCALE_FWD_H => 1
__DARWIN_FD_SET=__DARWIN_FD_SET(n, p) => do { int __fd = (n); ((p)->fds_bits[__fd/__DARWIN_NFDBITS] |= (1<<(__fd % __DARWIN_NFDBITS))); } while(0)
_POSIX_VERSION=_POSIX_VERSION => 200112L
_READ_OK=_READ_OK => (1<<9)
_GLIBCXX_HAVE_COSL=_GLIBCXX_HAVE_COSL => 1
_GLIBCXX_HAVE_LDEXPF=_GLIBCXX_HAVE_LDEXPF => 1
catch=catch(X) => if (false)
LC_MESSAGES=LC_MESSAGES => 6
__DARWIN_ALIAS_C=__DARWIN_ALIAS_C(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_NON_CANCELABLE __DARWIN_SUF_UNIX03)
_SC_TZNAME_MAX=_SC_TZNAME_MAX => 27
_SC_V6_ILP32_OFF32=_SC_V6_ILP32_OFF32 => 103
_SC_XOPEN_SHM=_SC_XOPEN_SHM => 113
__DARWIN_ALIAS=__DARWIN_ALIAS(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_UNIX03)
__IDSTRING=__IDSTRING(name, string) => static const char name[] __used = string
__restrict=__restrict
_BASIC_STRING_TCC=_BASIC_STRING_TCC => 1
_POSIX_SPORADIC_SERVER=_POSIX_SPORADIC_SERVER => (-1)
__GTHREAD_ONCE_INIT=__GTHREAD_ONCE_INIT => PTHREAD_ONCE_INIT
_POSIX_SEM_VALUE_MAX=_POSIX_SEM_VALUE_MAX => 32767
_PTHREAD_KEY_T=_PTHREAD_KEY_T
_SC_LOGIN_NAME_MAX=_SC_LOGIN_NAME_MAX => 73
WIFEXITED=WIFEXITED(x) => (_WSTATUS(x) == 0)
_SIGSET_T=_SIGSET_T
__SRW=__SRW => 0x0010
INT_FAST64_MAX=INT_FAST64_MAX => INT64_MAX
_SC_TRACE_NAME_MAX=_SC_TRACE_NAME_MAX => 128
_POSIX_THREADS=_POSIX_THREADS => 200112L
BYTE_ORDER=BYTE_ORDER => __DARWIN_BYTE_ORDER
va_end=va_end(ap) => va_end (ap)
_GLIBCXX_IOSFWD=_GLIBCXX_IOSFWD => 1
INT_LEAST64_MAX=INT_LEAST64_MAX => INT64_MAX
__sclearerr=__sclearerr(p) => ((void)((p)->_flags &= ~(__SERR|__SEOF)))
_PC_NAME_CHARS_MAX=_PC_NAME_CHARS_MAX => 10
QUAD_MAX=QUAD_MAX => LLONG_MAX
_GLIBCXX_WEAK_DEFINITION=_GLIBCXX_WEAK_DEFINITION => __attribute__ ((weak))
_GLIBCXX_BEGIN_LDBL_NAMESPACE=_GLIBCXX_BEGIN_LDBL_NAMESPACE
SIGEV_NONE=SIGEV_NONE => 0
_UINT64_T=_UINT64_T
__LP64_OFF64=__LP64_OFF64 => (-1)
_GLIBCXX_PACKAGE_STRING=_GLIBCXX_PACKAGE_STRING => "package-unused version-unused"
w_coredump=w_coredump => w_T.w_Coredump
_GLIBCXX_HAVE_LDEXPL=_GLIBCXX_HAVE_LDEXPL => 1
_PTHREAD_RWLOCKATTR_T=_PTHREAD_RWLOCKATTR_T
_POSIX_THREAD_SAFE_FUNCTIONS=_POSIX_THREAD_SAFE_FUNCTIONS => 200112L
SIGURG=SIGURG => 16
_INT64_T=_INT64_T
_SC_SEMAPHORES=_SC_SEMAPHORES => 37
__DARWIN_WCTYPE_TOP_static_inline=__DARWIN_WCTYPE_TOP_static_inline => static __inline
_POSIX_MAPPED_FILES=_POSIX_MAPPED_FILES => 200112L
INTMAX_MAX=INTMAX_MAX => INT64_MAX
_LOCALE_CLASSES_H=_LOCALE_CLASSES_H => 1
SIGSTKSZ=SIGSTKSZ => 131072
G_BYTE_ORDER=G_BYTE_ORDER => 1234
__AVAILABILITY_INTERNAL__=__AVAILABILITY_INTERNAL__
__IPHONE_NA=__IPHONE_NA => 99999
_GLIBCXX_HAVE_WCSTOF=_GLIBCXX_HAVE_WCSTOF => 1
CHARCLASS_NAME_MAX=CHARCLASS_NAME_MAX => 14
SIGIO=SIGIO => 23
_GLIBCXX_ISTREAM=_GLIBCXX_ISTREAM => 1
WINT_MIN=WINT_MIN => INT32_MIN
_GLIBCXX_HAVE_STRERROR_R=_GLIBCXX_HAVE_STRERROR_R => 1
__unavailable=__unavailable
_GLIBCXX_END_LDBL_NAMESPACE=_GLIBCXX_END_LDBL_NAMESPACE
CXA_RUNTIME_CXA_EXCEPTION_THROW=CXA_RUNTIME_CXA_EXCEPTION_THROW(arg0) => do { __asm__ volatile(".reference " CXA_RUNTIME_TYPEDEFS); __dtrace_probe$cxa_runtime$cxa_exception_throw$v1$766f6964202a(arg0); __asm__ volatile(".reference " CXA_RUNTIME_STABILITY); } while (0)
_GLIBCXX_END_NESTED_NAMESPACE=_GLIBCXX_END_NESTED_NAMESPACE => _GLIBCXX_END_NAMESPACE
_POSIX_THREAD_CPUTIME=_POSIX_THREAD_CPUTIME => (-1)
_SC_MQ_PRIO_MAX=_SC_MQ_PRIO_MAX => 75
_GLIBCXX_PACKAGE_TARNAME=_GLIBCXX_PACKAGE_TARNAME => "libstdc++"
CHILD_MAX=CHILD_MAX => 266
_CS_XBS5_ILP32_OFF32_LDFLAGS=_CS_XBS5_ILP32_OFF32_LDFLAGS => 21
ru_first=ru_first => ru_ixrss
_GLIBCXX_HAVE_COSF=_GLIBCXX_HAVE_COSF => 1
_GLIBCXX_NAMESPACE_ASSOCIATION_VERSION=_GLIBCXX_NAMESPACE_ASSOCIATION_VERSION => 0
_GLIBCXX_RES_LIMITS=_GLIBCXX_RES_LIMITS => 1
getchar_unlocked=getchar_unlocked() => getc_unlocked(stdin)
TRAP_BRKPT=TRAP_BRKPT => 1
_CS_XBS5_ILP32_OFFBIG_LINTFLAGS=_CS_XBS5_ILP32_OFFBIG_LINTFLAGS => 27
UINT_LEAST8_MAX=UINT_LEAST8_MAX => UINT8_MAX
WCHAR_MAX=WCHAR_MAX => __DARWIN_WCHAR_MAX
___POSIX_C_DEPRECATED_STARTING_200809L=___POSIX_C_DEPRECATED_STARTING_200809L
_POSIX_TRACE_EVENT_NAME_MAX=_POSIX_TRACE_EVENT_NAME_MAX => 30
_GLIBCXX_CSTDLIB=_GLIBCXX_CSTDLIB => 1
RE_DUP_MAX=RE_DUP_MAX => 255
SIGTERM=SIGTERM => 15
M_I86=M_I86 => 1
L_INCR=L_INCR => SEEK_CUR
fwopen=fwopen(cookie, fn) => funopen(cookie, 0, fn, 0, 0)
UINT_FAST32_MAX=UINT_FAST32_MAX => UINT32_MAX
_POSIX_BARRIERS=_POSIX_BARRIERS => (-1)
ILL_COPROC=ILL_COPROC => 7
SA_64REGSET=SA_64REGSET => 0x0200
_PTHREAD_T=_PTHREAD_T
SIZE_T_MAX=SIZE_T_MAX => ULONG_MAX
_XOPEN_STREAMS=_XOPEN_STREAMS => (-1)
PTHREAD_CANCEL_ASYNCHRONOUS=PTHREAD_CANCEL_ASYNCHRONOUS => 0x00
FPE_FLTUND=FPE_FLTUND => 3
_UUID_T=_UUID_T
SHRT_MAX=SHRT_MAX => 32767
_PTHREAD_H=_PTHREAD_H
RLIMIT_CORE=RLIMIT_CORE => 4
POLL_ERR=POLL_ERR => 4
_GLIBCXX_PACKAGE_NAME=_GLIBCXX_PACKAGE_NAME => "package-unused"
CLD_CONTINUED=CLD_CONTINUED => 6
_SC_2_VERSION=_SC_2_VERSION => 17
_PC_REC_XFER_ALIGN=_PC_REC_XFER_ALIGN => 23
_POSIX2_BC_BASE_MAX=_POSIX2_BC_BASE_MAX => 99
__DARWIN_ALIAS_STARTING_MAC___MAC_10_2=__DARWIN_ALIAS_STARTING_MAC___MAC_10_2(x)
_ALLOCA_H_=_ALLOCA_H_
__DARWIN_ALIAS_STARTING_MAC___MAC_10_3=__DARWIN_ALIAS_STARTING_MAC___MAC_10_3(x)
__DARWIN_ALIAS_STARTING_MAC___MAC_10_0=__DARWIN_ALIAS_STARTING_MAC___MAC_10_0(x)
__DARWIN_ALIAS_STARTING_MAC___MAC_10_1=__DARWIN_ALIAS_STARTING_MAC___MAC_10_1(x)
__DARWIN_ALIAS_STARTING_MAC___MAC_10_6=__DARWIN_ALIAS_STARTING_MAC___MAC_10_6(x)
__DARWIN_ALIAS_STARTING_MAC___MAC_10_7=__DARWIN_ALIAS_STARTING_MAC___MAC_10_7(x)
_CS_XBS5_LPBIG_OFFBIG_LIBS=_CS_XBS5_LPBIG_OFFBIG_LIBS => 34
_GLIBCXX_UTILITY=_GLIBCXX_UTILITY => 1
POLL_PRI=POLL_PRI => 5
__DARWIN_ALIAS_STARTING_MAC___MAC_10_4=__DARWIN_ALIAS_STARTING_MAC___MAC_10_4(x)
_GLIBCXX_USE_C99_FENV_TR1=_GLIBCXX_USE_C99_FENV_TR1 => 1
LC_MONETARY=LC_MONETARY => 3
__DARWIN_ALIAS_STARTING_MAC___MAC_10_5=__DARWIN_ALIAS_STARTING_MAC___MAC_10_5(x)
_POSIX_THREAD_PROCESS_SHARED=_POSIX_THREAD_PROCESS_SHARED => 200112L
_POSIX_THREAD_PRIORITY_SCHEDULING=_POSIX_THREAD_PRIORITY_SCHEDULING => (-1)
_POSIX_TRACE=_POSIX_TRACE => (-1)
RUSAGE_CHILDREN=RUSAGE_CHILDREN => -1
_GLIBCXX_OS_DEFINES=_GLIBCXX_OS_DEFINES => 1
INT32_MAX=INT32_MAX => 2147483647
_PTHREAD_CONDATTR_T=_PTHREAD_CONDATTR_T
_CT_RUNE_T=_CT_RUNE_T
__IPHONE_2_0=__IPHONE_2_0 => 20000
_BSD_MACHINE_ENDIAN_H_=_BSD_MACHINE_ENDIAN_H_
_POSIX_TRACE_NAME_MAX=_POSIX_TRACE_NAME_MAX => 8
__IPHONE_2_1=__IPHONE_2_1 => 20100
_I386__LIMITS_H_=_I386__LIMITS_H_
__IPHONE_2_2=__IPHONE_2_2 => 20200
__TYPES_H_=__TYPES_H_
_IOLBF=_IOLBF => 1
_POSIX_V6_ILP32_OFFBIG=_POSIX_V6_ILP32_OFFBIG => __ILP32_OFFBIG
__need_stack_t=__need_stack_t
_PTHREAD_COND_SIG_init=_PTHREAD_COND_SIG_init => 0x3CB0B1BB
_GLIBCXX_HAVE_ICONV=_GLIBCXX_HAVE_ICONV => 1
UQUAD_MAX=UQUAD_MAX => ULLONG_MAX
_SC_ARG_MAX=_SC_ARG_MAX => 1
_GLIBCXX_HAVE_POWF=_GLIBCXX_HAVE_POWF => 1
_GLIBCXX_HAVE_STRTOF=_GLIBCXX_HAVE_STRTOF => 1
_ITERATOR_BASE_FUNCS_H=_ITERATOR_BASE_FUNCS_H => 1
_SC_2_PBS_TRACK=_SC_2_PBS_TRACK => 64
_LOCALE_FACETS_H=_LOCALE_FACETS_H => 1
SSIZE_MAX=SSIZE_MAX => LONG_MAX
_INT16_T=_INT16_T
QUAD_MIN=QUAD_MIN => LLONG_MIN
_GLIBCXX_HAVE_POWL=_GLIBCXX_HAVE_POWL => 1
_EXCEPTION_DEFINES_H=_EXCEPTION_DEFINES_H => 1
__AVAILABILITY_INTERNAL_UNAVAILABLE=__AVAILABILITY_INTERNAL_UNAVAILABLE => __attribute__((unavailable,visibility("default")))
_SC_V6_LPBIG_OFFBIG=_SC_V6_LPBIG_OFFBIG => 106
__SNPT=__SNPT => 0x0800
_GLIBCXX_HAVE_WRITEV=_GLIBCXX_HAVE_WRITEV => 1
_PC_XATTR_SIZE_BITS=_PC_XATTR_SIZE_BITS => 26
_GLIBCXX_USE_C99_MATH=_GLIBCXX_USE_C99_MATH => 1
_IONBF=_IONBF => 2
__STDC__=__STDC__ => 1
__sfeof=__sfeof(p) => (((p)->_flags & __SEOF) != 0)
__DARWIN_LITTLE_ENDIAN=__DARWIN_LITTLE_ENDIAN => 1234
_SC_CLK_TCK=_SC_CLK_TCK => 3
___POSIX_C_DEPRECATED_STARTING_199209L=___POSIX_C_DEPRECATED_STARTING_199209L
__PTHREAD_ATTR_SIZE__=__PTHREAD_ATTR_SIZE__ => 36
INT_LEAST16_MAX=INT_LEAST16_MAX => INT16_MAX
_GLIBCXX_HAVE_COMPLEX_H=_GLIBCXX_HAVE_COMPLEX_H => 1
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_4_3=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_4_3(x)
__SCCSID=__SCCSID(s) => __IDSTRING(sccsid,s)
BC_STRING_MAX=BC_STRING_MAX => 1000
_GLIBCXX_CWCHAR=_GLIBCXX_CWCHAR => 1
FPE_FLTINV=FPE_FLTINV => 5
SIG_HOLD=SIG_HOLD => (void (*)(int))5
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_4_0=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_4_0(x)
__DARWIN_FD_CLR=__DARWIN_FD_CLR(n, p) => do { int __fd = (n); ((p)->fds_bits[__fd/__DARWIN_NFDBITS] &= ~(1<<(__fd % __DARWIN_NFDBITS))); } while(0)
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_4_2=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_4_2(x)
__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_4_1=__DARWIN_ALIAS_STARTING_IPHONE___IPHONE_4_1(x)
WCOREFLAG=WCOREFLAG => 0200
INT_MAX=INT_MAX => 2147483647
UINT64_C=UINT64_C(v) => (v ## ULL)
_POSIX_V7_LP64_OFF64=_POSIX_V7_LP64_OFF64 => __LP64_OFF64
_POSIX_TYPED_MEMORY_OBJECTS=_POSIX_TYPED_MEMORY_OBJECTS => (-1)
WCONTINUED=WCONTINUED => 0x00000010
_POSIX_READER_WRITER_LOCKS=_POSIX_READER_WRITER_LOCKS => 200112L
_SYS__ENDIAN_H_=_SYS__ENDIAN_H_
__DARWIN_1050ALIAS_I=__DARWIN_1050ALIAS_I(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_1050 __DARWIN_SUF_64_BIT_INO_T __DARWIN_SUF_UNIX03)
_SC_2_PBS_ACCOUNTING=_SC_2_PBS_ACCOUNTING => 60
STDC_HEADERS=STDC_HEADERS => 1
__DARWIN_1050ALIAS_C=__DARWIN_1050ALIAS_C(sym) => __asm("_" __STRING(sym) __DARWIN_SUF_1050 __DARWIN_SUF_NON_CANCELABLE __DARWIN_SUF_UNIX03)
PRIO_USER=PRIO_USER => 2
PTHREAD_RWLOCK_INITIALIZER=PTHREAD_RWLOCK_INITIALIZER => {_PTHREAD_RWLOCK_SIG_init, {0}}
_SC_TRACE_INHERIT=_SC_TRACE_INHERIT => 99
_SC_XBS5_ILP32_OFFBIG=_SC_XBS5_ILP32_OFFBIG => 123
_VA_LIST=_VA_LIST
__PTHREAD_CONDATTR_SIZE__=__PTHREAD_CONDATTR_SIZE__ => 4
_CS_POSIX_V6_ILP32_OFF32_CFLAGS=_CS_POSIX_V6_ILP32_OFF32_CFLAGS => 2
_SC_SHARED_MEMORY_OBJECTS=_SC_SHARED_MEMORY_OBJECTS => 39
_SC_THREAD_PRIORITY_SCHEDULING=_SC_THREAD_PRIORITY_SCHEDULING => 89
SCHED_OTHER=SCHED_OTHER => 1
L_XTND=L_XTND => SEEK_END
__amd64__=__amd64__ => 1
SIGINFO=SIGINFO => 29
CAST_USER_ADDR_T=CAST_USER_ADDR_T(a_ptr) => ((user_addr_t)((uintptr_t)(a_ptr)))
_SC_EXPR_NEST_MAX=_SC_EXPR_NEST_MAX => 14
_GLIBCXX_HOSTED=_GLIBCXX_HOSTED => 1
_POSIX_MQ_PRIO_MAX=_POSIX_MQ_PRIO_MAX => 32
NZERO=NZERO => 20
_STRING_H_=_STRING_H_
RLIMIT_CPU=RLIMIT_CPU => 0
_GID_T=_GID_T
_CS_XBS5_ILP32_OFF32_LIBS=_CS_XBS5_ILP32_OFF32_LIBS => 22
PRIO_MIN=PRIO_MIN => -20
_SC_TRACE_LOG=_SC_TRACE_LOG => 100
_GLIBCXX_FAST_MATH=_GLIBCXX_FAST_MATH => 0
RLIMIT_NOFILE=RLIMIT_NOFILE => 8
SIGXFSZ=SIGXFSZ => 25
_WRITE_OK=_WRITE_OK => (1<<10)
_POSIX_SSIZE_MAX=_POSIX_SSIZE_MAX => 32767
_POSIX2_BC_DIM_MAX=_POSIX2_BC_DIM_MAX => 2048
_IOFBF=_IOFBF => 0
__deprecated=__deprecated
ACCESSX_MAX_TABLESIZE=ACCESSX_MAX_TABLESIZE => (16 * 1024)
_SC_SPIN_LOCKS=_SC_SPIN_LOCKS => 80
PTHREAD_RECURSIVE_MUTEX_INITIALIZER=PTHREAD_RECURSIVE_MUTEX_INITIALIZER => {_PTHREAD_RECURSIVE_MUTEX_SIG_init, {0}}
PRIO_DARWIN_PROCESS=PRIO_DARWIN_PROCESS => 4
_GLIBCXX_HAVE_INT64_T=_GLIBCXX_HAVE_INT64_T => 1
