package com.ochafik.lang.jnaerator.nativesupport.machoexport;
/**
 * JNA Wrapper for library <b>FatMachO</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface FatMachOLibrary extends com.sun.jna.Library {
	public static final com.ochafik.lang.jnaerator.nativesupport.machoexport.FatMachOLibrary INSTANCE = (com.ochafik.lang.jnaerator.nativesupport.machoexport.FatMachOLibrary)com.sun.jna.Native.loadLibrary(com.ochafik.lang.jnaerator.runtime.LibraryExtractor.getLibraryPath("FatMachO", true, com.ochafik.lang.jnaerator.nativesupport.machoexport.FatMachOLibrary.class), com.ochafik.lang.jnaerator.nativesupport.machoexport.FatMachOLibrary.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_SLINE = 68;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int MH_PRELOAD = 5;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int MH_INCRLINK = 2;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_RBRAC = 224;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i><br>
	 * (cpu_subtype_t)
	 */
	/**
	 * define<br>
	 * Conversion Error : int (The name 'long' is invalid for a Java field.)<br>
	 * SKIPPED:<br>
	 * <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i><br>
	 * int
	 */
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_SOL = 132;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_GSYM = 32;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i><br>
	 * (cpu_type_t)
	 */
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int LC_IDENT = 8;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int FAT_CIGAM = -341053524;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int FAT_MAGIC = -889275714;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_ENTRY = 164;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_LBRAC = 192;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_SECT = 14;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_PSYM = 160;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i><br>
	 * (cpu_subtype_t)
	 */
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_STSYM = 38;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int MH_MAGIC = -17958194;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int LC_IDFVMLIB = 7;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_STAB = 224;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int LC_FVMFILE = 9;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int MH_OBJECT = 1;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int LC_SEGMENT = 1;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_LSYM = 128;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int MH_NOUNDEFS = 1;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int LC_SYMTAB = 2;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_TEXT = 4;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_INDR = 10;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_ABS = 2;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_LENG = 254;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_ECOML = 232;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_FNAME = 34;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int LC_SYMSEG = 3;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int MH_CORE = 4;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int LC_LOADFVMLIB = 6;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_UNDF = 0;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_BSS = 8;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int MH_EXECUTE = 2;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int LC_UNIXTHREAD = 5;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int LC_THREAD = 4;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int MH_FVMLIB = 3;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_FUN = 36;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_ECOMM = 228;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_SSYM = 96;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_LCSYM = 40;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_BCOMM = 226;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_SO = 100;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_RSYM = 64;
	/// <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h</i>
	public static final int N_DATA = 6;
}
