package com.ochafik.lang.jnaerator.nativesupport.machoexport;
/**
 * <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h:42</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class mach_header extends com.ochafik.lang.jnaerator.runtime.Structure<mach_header, mach_header.ByValue, mach_header.ByReference> {
	/// Mach magic number identifier
	public int magic;
	/// cpu specifier
	public int cputype;
	/// machine specifier
	public int cpusubtype;
	/// type of file
	public int filetype;
	/// number of load commands
	public int ncmds;
	/// size of all load commands
	public int sizeofcmds;
	/// flags
	public int flags;
	public mach_header() {
		super();
	}
	/**
	 * @param magic Mach magic number identifier<br>
	 * @param cputype cpu specifier<br>
	 * @param cpusubtype machine specifier<br>
	 * @param filetype type of file<br>
	 * @param ncmds number of load commands<br>
	 * @param sizeofcmds size of all load commands<br>
	 * @param flags flags
	 */
	public mach_header(int magic, int cputype, int cpusubtype, int filetype, int ncmds, int sizeofcmds, int flags) {
		super();
		this.magic = magic;
		this.cputype = cputype;
		this.cpusubtype = cpusubtype;
		this.filetype = filetype;
		this.ncmds = ncmds;
		this.sizeofcmds = sizeofcmds;
		this.flags = flags;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected mach_header newInstance() { return new mach_header(); }
	public static class ByReference extends mach_header implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends mach_header implements com.sun.jna.Structure.ByValue {}
}
