package com.ochafik.lang.jnaerator.nativesupport.machoexport;
/**
 * <i>native declaration : sources/com/ochafik/lang/jnaerator/nativesupport/machoexport.h:69</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class symtab_command extends com.ochafik.lang.jnaerator.runtime.Structure<symtab_command, symtab_command.ByValue, symtab_command.ByReference> {
	/// LC_SYMTAB
	public int cmd;
	/// sizeof(struct symtab_command)
	public int cmdsize;
	/// symbol table offset
	public int symoff;
	/// number of symbol table entries
	public int nsyms;
	/// string table offset
	public int stroff;
	/// string table size in bytes
	public int strsize;
	public symtab_command() {
		super();
	}
	/**
	 * @param cmd LC_SYMTAB<br>
	 * @param cmdsize sizeof(struct symtab_command)<br>
	 * @param symoff symbol table offset<br>
	 * @param nsyms number of symbol table entries<br>
	 * @param stroff string table offset<br>
	 * @param strsize string table size in bytes
	 */
	public symtab_command(int cmd, int cmdsize, int symoff, int nsyms, int stroff, int strsize) {
		super();
		this.cmd = cmd;
		this.cmdsize = cmdsize;
		this.symoff = symoff;
		this.nsyms = nsyms;
		this.stroff = stroff;
		this.strsize = strsize;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected symtab_command newInstance() { return new symtab_command(); }
	public static class ByReference extends symtab_command implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends symtab_command implements com.sun.jna.Structure.ByValue {}
}
