package gtk;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Library;
/**
 * Note: directly manipulating structs is generally a bad idea, but<br>
 * in this case it's an *incredibly* bad idea, because all or part<br>
 * of this struct can be invalid at any given time. Use the functions,<br>
 * or you will get hosed, I promise.<br>
 * <i>native declaration : glib-2.0/glib/gdate.h:64</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Gtk") 
public abstract class _GDate extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : guint (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guint (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guint (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guint (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guint (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guint (failed to convert type to Java (undefined type)) */
}
