package gtk;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Library;
/**
 * GQueue:<br>
 * @head: a pointer to the first element of the queue<br>
 * @tail: a pointer to the last element of the queue<br>
 * @length: the number of elements in the queue<br>
 * * Contains the public fields of a<br>
 * <link linkend="glib-Double-ended-Queues">Queue</link>.<br>
 * <i>native declaration : glib-2.0/glib/gqueue.h:15</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Gtk") 
public abstract class _GQueue extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GList* (failed to convert type to Java (undefined type)) */
	/** Conversion Error : GList* (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guint (failed to convert type to Java (undefined type)) */
}
