package gtk;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Library;
/**
 * <i>native declaration : glib-2.0/glib/gthread.h:78</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Gtk") 
public abstract class _GRecMutex extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : gpointer (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guint[2] (failed to convert type to Java (undefined type)) */
}
