package gtk;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : glib-2.0/glib/gscanner.h:78</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("Gtk") 
public abstract class _GTokenValue extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : gpointer (failed to convert type to Java (undefined type)) */
	/** Conversion Error : gchar* (failed to convert type to Java (undefined type)) */
	/** Conversion Error : gulong (failed to convert type to Java (undefined type)) */
	/** Conversion Error : gulong (failed to convert type to Java (undefined type)) */
	/** Conversion Error : gulong (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guint64 (failed to convert type to Java (undefined type)) */
	/** Conversion Error : gdouble (failed to convert type to Java (undefined type)) */
	/** Conversion Error : gulong (failed to convert type to Java (undefined type)) */
	/** Conversion Error : gchar* (failed to convert type to Java (undefined type)) */
	/** Conversion Error : gchar* (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guchar (failed to convert type to Java (undefined type)) */
	/** Conversion Error : guint (failed to convert type to Java (undefined type)) */
}
