package gtk;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Bits;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : glib-2.0/glib/gtypes.h:415</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("Gtk") 
public class GDoubleIEEE754 extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : gdouble */
	@Field(0) 
	public double v_double() {
		return this.io.getDoubleField(this, 0);
	}
	/** C type : gdouble */
	@Field(0) 
	public GDoubleIEEE754 v_double(double v_double) {
		this.io.setDoubleField(this, 0, v_double);
		return this;
	}
	/** C type : mpn_struct */
	@Field(1) 
	public gtk.GFloatIEEE754.mpn_struct mpn() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : mpn_struct */
	@Field(1) 
	public GDoubleIEEE754 mpn(gtk.GFloatIEEE754.mpn_struct mpn) {
		this.io.setNativeObjectField(this, 1, mpn);
		return this;
	}
	/** <i>native declaration : glib-2.0/glib/gtypes.h:418</i> */
	public static class mpn_struct extends StructObject {
		static {
			BridJ.register();
		}
		/** C type : guint */
		@Field(0) 
		@Bits(32) 
		public int mantissa_low() {
			return this.io.getIntField(this, 0);
		}
		/** C type : guint */
		@Field(0) 
		@Bits(32) 
		public mpn_struct mantissa_low(int mantissa_low) {
			this.io.setIntField(this, 0, mantissa_low);
			return this;
		}
		/** C type : guint */
		@Field(1) 
		@Bits(20) 
		public int mantissa_high() {
			return this.io.getIntField(this, 1);
		}
		/** C type : guint */
		@Field(1) 
		@Bits(20) 
		public mpn_struct mantissa_high(int mantissa_high) {
			this.io.setIntField(this, 1, mantissa_high);
			return this;
		}
		/** C type : guint */
		@Field(2) 
		@Bits(11) 
		public int biased_exponent() {
			return this.io.getIntField(this, 2);
		}
		/** C type : guint */
		@Field(2) 
		@Bits(11) 
		public mpn_struct biased_exponent(int biased_exponent) {
			this.io.setIntField(this, 2, biased_exponent);
			return this;
		}
		/** C type : guint */
		@Field(3) 
		@Bits(1) 
		public int sign() {
			return this.io.getIntField(this, 3);
		}
		/** C type : guint */
		@Field(3) 
		@Bits(1) 
		public mpn_struct sign(int sign) {
			this.io.setIntField(this, 3, sign);
			return this;
		}
		public mpn_struct() {
			super();
		}
		public mpn_struct(Pointer pointer) {
			super(pointer);
		}
	};
	public GDoubleIEEE754() {
		super();
	}
	public GDoubleIEEE754(Pointer pointer) {
		super(pointer);
	}
}
