package gtk;
import gtk.GtkLibrary.GIOCondition;
import gtk.GtkLibrary.GIOFlags;
import gtk.GtkLibrary.GIOStatus;
import gtk.GtkLibrary.GSeekType;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.FlagSet;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : glib-2.0/glib/giochannel.h:131</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Gtk") 
public class GIOFuncs extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : io_read_callback* */
	@Field(0) 
	public Pointer<GIOFuncs.io_read_callback > io_read() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : io_read_callback* */
	@Field(0) 
	public GIOFuncs io_read(Pointer<GIOFuncs.io_read_callback > io_read) {
		this.io.setPointerField(this, 0, io_read);
		return this;
	}
	/** C type : io_write_callback* */
	@Field(1) 
	public Pointer<GIOFuncs.io_write_callback > io_write() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : io_write_callback* */
	@Field(1) 
	public GIOFuncs io_write(Pointer<GIOFuncs.io_write_callback > io_write) {
		this.io.setPointerField(this, 1, io_write);
		return this;
	}
	/** C type : io_seek_callback* */
	@Field(2) 
	public Pointer<GIOFuncs.io_seek_callback > io_seek() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : io_seek_callback* */
	@Field(2) 
	public GIOFuncs io_seek(Pointer<GIOFuncs.io_seek_callback > io_seek) {
		this.io.setPointerField(this, 2, io_seek);
		return this;
	}
	/** C type : io_close_callback* */
	@Field(3) 
	public Pointer<GIOFuncs.io_close_callback > io_close() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : io_close_callback* */
	@Field(3) 
	public GIOFuncs io_close(Pointer<GIOFuncs.io_close_callback > io_close) {
		this.io.setPointerField(this, 3, io_close);
		return this;
	}
	/** C type : io_create_watch_callback* */
	@Field(4) 
	public Pointer<GIOFuncs.io_create_watch_callback > io_create_watch() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : io_create_watch_callback* */
	@Field(4) 
	public GIOFuncs io_create_watch(Pointer<GIOFuncs.io_create_watch_callback > io_create_watch) {
		this.io.setPointerField(this, 4, io_create_watch);
		return this;
	}
	/** C type : io_free_callback* */
	@Field(5) 
	public Pointer<GIOFuncs.io_free_callback > io_free() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : io_free_callback* */
	@Field(5) 
	public GIOFuncs io_free(Pointer<GIOFuncs.io_free_callback > io_free) {
		this.io.setPointerField(this, 5, io_free);
		return this;
	}
	/** C type : io_set_flags_callback* */
	@Field(6) 
	public Pointer<GIOFuncs.io_set_flags_callback > io_set_flags() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : io_set_flags_callback* */
	@Field(6) 
	public GIOFuncs io_set_flags(Pointer<GIOFuncs.io_set_flags_callback > io_set_flags) {
		this.io.setPointerField(this, 6, io_set_flags);
		return this;
	}
	/** C type : io_get_flags_callback* */
	@Field(7) 
	public Pointer<GIOFuncs.io_get_flags_callback > io_get_flags() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : io_get_flags_callback* */
	@Field(7) 
	public GIOFuncs io_get_flags(Pointer<GIOFuncs.io_get_flags_callback > io_get_flags) {
		this.io.setPointerField(this, 7, io_get_flags);
		return this;
	}
	/** <i>native declaration : glib-2.0/glib/giochannel.h</i> */
	public static abstract class io_read_callback extends Callback<io_read_callback > {
		public final IntValuedEnum<GIOStatus > apply(Pointer<GIOChannel > channel, Pointer<Byte > buf, @org.bridj.ann.CLong long count, Pointer<org.bridj.CLong > bytes_read, Pointer<Pointer<GError > > err) {
			return FlagSet.fromValue(apply(Pointer.getPeer(channel), Pointer.getPeer(buf), count, Pointer.getPeer(bytes_read), Pointer.getPeer(err)), GIOStatus.class);
		}
		public abstract int apply(@Ptr long channel, @Ptr long buf, @org.bridj.ann.CLong long count, @Ptr long bytes_read, @Ptr long err);
	};
	/** <i>native declaration : glib-2.0/glib/giochannel.h</i> */
	public static abstract class io_write_callback extends Callback<io_write_callback > {
		public final IntValuedEnum<GIOStatus > apply(Pointer<GIOChannel > channel, Pointer<Byte > buf, @org.bridj.ann.CLong long count, Pointer<org.bridj.CLong > bytes_written, Pointer<Pointer<GError > > err) {
			return FlagSet.fromValue(apply(Pointer.getPeer(channel), Pointer.getPeer(buf), count, Pointer.getPeer(bytes_written), Pointer.getPeer(err)), GIOStatus.class);
		}
		public abstract int apply(@Ptr long channel, @Ptr long buf, @org.bridj.ann.CLong long count, @Ptr long bytes_written, @Ptr long err);
	};
	/** <i>native declaration : glib-2.0/glib/giochannel.h</i> */
	public static abstract class io_seek_callback extends Callback<io_seek_callback > {
		public final IntValuedEnum<GIOStatus > apply(Pointer<GIOChannel > channel, long offset, IntValuedEnum<GSeekType > type, Pointer<Pointer<GError > > err) {
			return FlagSet.fromValue(apply(Pointer.getPeer(channel), offset, (int)type.value(), Pointer.getPeer(err)), GIOStatus.class);
		}
		public abstract int apply(@Ptr long channel, long offset, int type, @Ptr long err);
	};
	/** <i>native declaration : glib-2.0/glib/giochannel.h</i> */
	public static abstract class io_close_callback extends Callback<io_close_callback > {
		public final IntValuedEnum<GIOStatus > apply(Pointer<GIOChannel > channel, Pointer<Pointer<GError > > err) {
			return FlagSet.fromValue(apply(Pointer.getPeer(channel), Pointer.getPeer(err)), GIOStatus.class);
		}
		public abstract int apply(@Ptr long channel, @Ptr long err);
	};
	/** <i>native declaration : glib-2.0/glib/giochannel.h</i> */
	public static abstract class io_create_watch_callback extends Callback<io_create_watch_callback > {
		public final Pointer<GSource > apply(Pointer<GIOChannel > channel, IntValuedEnum<GIOCondition > condition) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(channel), (int)condition.value()), GSource.class);
		}
		@Ptr 
		public abstract long apply(@Ptr long channel, int condition);
	};
	/** <i>native declaration : glib-2.0/glib/giochannel.h</i> */
	public static abstract class io_free_callback extends Callback<io_free_callback > {
		public final void apply(Pointer<GIOChannel > channel) {
			apply(Pointer.getPeer(channel));
		}
		public abstract void apply(@Ptr long channel);
	};
	/** <i>native declaration : glib-2.0/glib/giochannel.h</i> */
	public static abstract class io_set_flags_callback extends Callback<io_set_flags_callback > {
		public final IntValuedEnum<GIOStatus > apply(Pointer<GIOChannel > channel, IntValuedEnum<GIOFlags > flags, Pointer<Pointer<GError > > err) {
			return FlagSet.fromValue(apply(Pointer.getPeer(channel), (int)flags.value(), Pointer.getPeer(err)), GIOStatus.class);
		}
		public abstract int apply(@Ptr long channel, int flags, @Ptr long err);
	};
	/** <i>native declaration : glib-2.0/glib/giochannel.h</i> */
	public static abstract class io_get_flags_callback extends Callback<io_get_flags_callback > {
		public final IntValuedEnum<GIOFlags > apply(Pointer<GIOChannel > channel) {
			return FlagSet.fromValue(apply(Pointer.getPeer(channel)), GIOFlags.class);
		}
		public abstract int apply(@Ptr long channel);
	};
	public GIOFuncs() {
		super();
	}
	public GIOFuncs(Pointer pointer) {
		super(pointer);
	}
}
