package gtk;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : glib-2.0/glib/glist.h:39</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Gtk") 
public abstract class GList extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : gpointer (Unsupported type) */
	/** C type : GList* */
	@Field(1) 
	public Pointer<GList > next() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : GList* */
	@Field(1) 
	public GList next(Pointer<GList > next) {
		this.io.setPointerField(this, 1, next);
		return this;
	}
	/** C type : GList* */
	@Field(2) 
	public Pointer<GList > prev() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : GList* */
	@Field(2) 
	public GList prev(Pointer<GList > prev) {
		this.io.setPointerField(this, 2, prev);
		return this;
	}
}
