package gtk;
import gtk.GtkLibrary.GOnceStatus;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : glib-2.0/glib/gthread.h:102</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Gtk") 
public abstract class GOnce extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : volatile GOnceStatus */
	@Field(0) 
	public IntValuedEnum<GOnceStatus > status() {
		return this.io.getEnumField(this, 0);
	}
	/** C type : volatile GOnceStatus */
	@Field(0) 
	public GOnce status(IntValuedEnum<GOnceStatus > status) {
		this.io.setEnumField(this, 0, status);
		return this;
	}
	/** Conversion Error : volatile gpointer (Unsupported type) */
}
