package gtk;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : glib-2.0/glib/gstring.h:41</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Gtk") 
public class GString extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : gchar* */
	@Field(0) 
	public Pointer<Byte > str() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : gchar* */
	@Field(0) 
	public GString str(Pointer<Byte > str) {
		this.io.setPointerField(this, 0, str);
		return this;
	}
	/** C type : gsize */
	@CLong 
	@Field(1) 
	public long len() {
		return this.io.getCLongField(this, 1);
	}
	/** C type : gsize */
	@CLong 
	@Field(1) 
	public GString len(long len) {
		this.io.setCLongField(this, 1, len);
		return this;
	}
	/** C type : gsize */
	@CLong 
	@Field(2) 
	public long allocated_len() {
		return this.io.getCLongField(this, 2);
	}
	/** C type : gsize */
	@CLong 
	@Field(2) 
	public GString allocated_len(long allocated_len) {
		this.io.setCLongField(this, 2, allocated_len);
		return this;
	}
	public GString() {
		super();
	}
	public GString(Pointer pointer) {
		super(pointer);
	}
}
