package gtk;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : glib-2.0/glib/gtypes.h:451</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Gtk") 
public class GTimeVal extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : glong */
	@CLong 
	@Field(0) 
	public long tv_sec() {
		return this.io.getCLongField(this, 0);
	}
	/** C type : glong */
	@CLong 
	@Field(0) 
	public GTimeVal tv_sec(long tv_sec) {
		this.io.setCLongField(this, 0, tv_sec);
		return this;
	}
	/** C type : glong */
	@CLong 
	@Field(1) 
	public long tv_usec() {
		return this.io.getCLongField(this, 1);
	}
	/** C type : glong */
	@CLong 
	@Field(1) 
	public GTimeVal tv_usec(long tv_usec) {
		this.io.setCLongField(this, 1, tv_usec);
		return this;
	}
	public GTimeVal() {
		super();
	}
	public GTimeVal(Pointer pointer) {
		super(pointer);
	}
}
