package com.ochafik.lang.jnaerator.nativesupport.dllexport;
/**
 * <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IMAGE_DATA_DIRECTORY extends com.ochafik.lang.jnaerator.runtime.Structure<IMAGE_DATA_DIRECTORY, IMAGE_DATA_DIRECTORY.ByValue, IMAGE_DATA_DIRECTORY.ByReference> {
	public int VirtualAddress;
	public int Size;
	public IMAGE_DATA_DIRECTORY() {
		super();
	}
	public IMAGE_DATA_DIRECTORY(int VirtualAddress, int Size) {
		super();
		this.VirtualAddress = VirtualAddress;
		this.Size = Size;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected IMAGE_DATA_DIRECTORY newInstance() { return new IMAGE_DATA_DIRECTORY(); }
	public static class ByReference extends IMAGE_DATA_DIRECTORY implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends IMAGE_DATA_DIRECTORY implements com.sun.jna.Structure.ByValue {}
}
