package com.ochafik.lang.jnaerator.nativesupport.dllexport;
/**
 * <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IMAGE_SECTION_HEADER extends com.ochafik.lang.jnaerator.runtime.Structure<IMAGE_SECTION_HEADER, IMAGE_SECTION_HEADER.ByValue, IMAGE_SECTION_HEADER.ByReference> {
	public byte[] Name = new byte[(8)];
	public Misc_union Misc;
	public int VirtualAddress;
	public int SizeOfRawData;
	public int PointerToRawData;
	public int PointerToRelocations;
	public int PointerToLinenumbers;
	public short NumberOfRelocations;
	public short NumberOfLinenumbers;
	public int Characteristics;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h:94</i>
	public static class Misc_union extends com.ochafik.lang.jnaerator.runtime.Union<Misc_union, Misc_union.ByValue, Misc_union.ByReference> {
		public int PhysicalAddress;
		public int VirtualSize;
		public Misc_union() {
			super();
		}
		public Misc_union(int PhysicalAddress_or_VirtualSize) {
			super();
			this.VirtualSize = this.PhysicalAddress = PhysicalAddress_or_VirtualSize;
			setType(Integer.TYPE);
		}
		protected ByReference newByReference() { return new ByReference(); }
		protected ByValue newByValue() { return new ByValue(); }
		protected Misc_union newInstance() { return new Misc_union(); }
		public static class ByReference extends Misc_union implements com.sun.jna.Structure.ByReference {}
		public static class ByValue extends Misc_union implements com.sun.jna.Structure.ByValue {}
	}
	public IMAGE_SECTION_HEADER() {
		super();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected IMAGE_SECTION_HEADER newInstance() { return new IMAGE_SECTION_HEADER(); }
	public static class ByReference extends IMAGE_SECTION_HEADER implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends IMAGE_SECTION_HEADER implements com.sun.jna.Structure.ByValue {}
}
