package com.ochafik.lang.jnaerator.nativesupport.dllexport;
/**
 * <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IMAGE_DOS_HEADER extends com.ochafik.lang.jnaerator.runtime.Structure<IMAGE_DOS_HEADER, IMAGE_DOS_HEADER.ByValue, IMAGE_DOS_HEADER.ByReference> {
	/// Magic number
	public short e_magic;
	/// Bytes on last page of file
	public short e_cblp;
	/// Pages in file
	public short e_cp;
	/// Relocations
	public short e_crlc;
	/// Size of header in paragraphs
	public short e_cparhdr;
	/// Minimum extra paragraphs needed
	public short e_minalloc;
	/// Maximum extra paragraphs needed
	public short e_maxalloc;
	/// Initial (relative) SS value
	public short e_ss;
	/// Initial SP value
	public short e_sp;
	/// Checksum
	public short e_csum;
	/// Initial IP value
	public short e_ip;
	/// Initial (relative) CS value
	public short e_cs;
	/// File address of relocation table
	public short e_lfarlc;
	/// Overlay number
	public short e_ovno;
	/// Reserved words
	public short[] e_res = new short[(4)];
	/// OEM identifier (for e_oeminfo)
	public short e_oemid;
	/// OEM information; e_oemid specific
	public short e_oeminfo;
	/// Reserved words
	public short[] e_res2 = new short[(10)];
	/// File address of new exe header
	public com.sun.jna.NativeLong e_lfanew;
	public IMAGE_DOS_HEADER() {
		super();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected IMAGE_DOS_HEADER newInstance() { return new IMAGE_DOS_HEADER(); }
	public static class ByReference extends IMAGE_DOS_HEADER implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends IMAGE_DOS_HEADER implements com.sun.jna.Structure.ByValue {}
}
